/**
 * Google Keyword Planner, as exported on 27 September 2026: average monthly
 * searches in India and the competition for ads. Rebuild by exporting again
 * and pasting the rows in; keys are lower case.
 *
 * The planner rounds averages into buckets (50, 500, 5,000), so a volume is
 * shown as the range it stands for rather than as a precise count.
 */

export const KEYWORD_STATS_DATE = "2026-09-27";

export const KEYWORD_STATS: Record<string, [number | null, string | null]> = {
  "100 job guarantee course data science": [50, "High"],
  "100 job guarantee data science course": [50, "Medium"],
  "100 placement data science": [50, "Unknown"],
  "ai agent development company": [5000, "Low"],
  "application software bespoke": [50, "Low"],
  "bespoke application": [50, "Low"],
  "bespoke application development": [50, "Low"],
  "bespoke application software": [50, "Low"],
  "bespoke development agency": [0, "Unknown"],
  "bespoke development company": [50, "Low"],
  "bespoke development software": [50, "Low"],
  "bespoke it application": [50, "Unknown"],
  "bespoke it software": [50, "Unknown"],
  "bespoke software": [500, "Low"],
  "bespoke software application development": [50, "Unknown"],
  "bespoke software company": [50, "Low"],
  "bespoke software developers": [50, "Unknown"],
  "bespoke software development": [50, "Medium"],
  "bespoke software development agency": [50, "Medium"],
  "bespoke software development company": [50, "Low"],
  "bespoke software development firm": [50, "Unknown"],
  "bespoke software development service": [5000, "Low"],
  "bespoke software product": [50, "Unknown"],
  "bespoke software programmers": [0, "Unknown"],
  "best custom software companies": [50, "Unknown"],
  "best custom software developers": [50, "Low"],
  "best custom software development": [50, "Unknown"],
  "best custom software development companies": [50, "Low"],
  "best data analytics courses with placement": [500, "High"],
  "best data science course with job guarantee": [50, "High"],
  "best data science course with placement guarantee": [500, "Medium"],
  "best data science courses with placement": [50, "Medium"],
  "best data science institute with placement": [50, "High"],
  "best data science job guarantee program": [50, "High"],
  "best data scientist course with placement": [50, "Medium"],
  "best digital marketing agencies for small business": [50, "Low"],
  "best digital marketing services for small business": [50, "Low"],
  "best institute for data science with placement": [50, "Medium"],
  "best internet marketing company for small business": [50, "Unknown"],
  "best marketing agency for small business": [50, "Low"],
  "best marketing firms for small business": [50, "Low"],
  "best online course for data science with placement": [50, "High"],
  "best online data science course with placement": [50, "High"],
  "best online marketing companies for small business": [50, "Low"],
  "best small digital agencies": [0, "Unknown"],
  "best small marketing agencies": [50, "Unknown"],
  "best social media marketing companies for small business": [50, "Unknown"],
  "big data analytics training and placement": [50, "Unknown"],
  "big data course with placement": [50, "Unknown"],
  "big data training and placement": [50, "Unknown"],
  "big data training with job guarantee": [50, "Unknown"],
  "business custom software": [50, "Low"],
  "content marketing agency for small business": [50, "Unknown"],
  "course in data science with placement": [50, "High"],
  "custom application developer": [50, "Medium"],
  "custom application development agency": [50, "Low"],
  "custom application development company": [500, "Low"],
  "custom application development firm": [50, "Unknown"],
  "custom application development services": [500, "Low"],
  "custom application software development": [50, "Low"],
  "custom application software development company": [50, "Unknown"],
  "custom business software company": [50, "Unknown"],
  "custom business software development company": [50, "Low"],
  "custom development company": [50, "Low"],
  "custom development firm": [0, "Unknown"],
  "custom enterprise application": [50, "Low"],
  "custom enterprise application development": [50, "Low"],
  "custom enterprise application development company": [50, "Unknown"],
  "custom enterprise software": [50, "Low"],
  "custom enterprise software company": [50, "Low"],
  "custom enterprise software development": [50, "Low"],
  "custom enterprise software development company": [50, "Low"],
  "custom enterprise software development services": [50, "Low"],
  "custom it software solution development company": [0, "Unknown"],
  "custom programming company": [50, "Unknown"],
  "custom software agency": [50, "Medium"],
  "custom software and application development services": [50, "Low"],
  "custom software application": [500, "Low"],
  "custom software application development companies": [50, "Unknown"],
  "custom software application development company": [50, "Low"],
  "custom software application development services": [50, "Low"],
  "custom software business": [50, "Low"],
  "custom software company": [50, "Low"],
  "custom software consultancy": [50, "Low"],
  "custom software design": [50, "Low"],
  "custom software developed for a specific company": [0, "Unknown"],
  "custom software developer": [50, "Low"],
  "custom software development": [5000, "Low"],
  "custom software development agency": [5000, "Low"],
  "custom software development business": [50, "Low"],
  "custom software development company": [5000, "Low"],
  "custom software development firms": [5000, "Low"],
  "custom software development for enterprise": [50, "Low"],
  "custom software development for startups": [50, "Low"],
  "custom software development near me": [50, "Low"],
  "custom software development outsourcing": [50, "Low"],
  "custom software development services": [5000, "Low"],
  "custom software development services company": [50, "Low"],
  "custom software development services near me": [50, "Low"],
  "custom software development solutions": [50, "Low"],
  "custom software development startups": [50, "Low"],
  "custom software development vendor": [50, "Low"],
  "custom software firm": [50, "Low"],
  "custom software near me": [50, "Low"],
  "custom software outsourcing": [50, "Unknown"],
  "custom software product development": [50, "Low"],
  "custom software product development company": [50, "Medium"],
  "custom software product development services": [50, "Low"],
  "custom software programming company": [0, "Unknown"],
  "data analytics course with 100 placement guarantee": [50, "High"],
  "data analytics course with job guarantee": [50, "Medium"],
  "data analytics course with placement": [500, "High"],
  "data analytics courses online with placement": [50, "High"],
  "data analytics courses with 100 placement": [50, "High"],
  "data analytics placement course": [50, "High"],
  "data science 100 job guarantee": [50, "High"],
  "data science 100 percent placement": [50, "High"],
  "data science 100 placement": [50, "Unknown"],
  "data science certification course with placement": [50, "Medium"],
  "data science certification with placement": [50, "High"],
  "data science course and placement": [50, "Medium"],
  "data science course job guarantee": [50, "Medium"],
  "data science course near me with placement": [50, "High"],
  "data science course online with placement": [500, "High"],
  "data science course placement": [50, "Medium"],
  "data science course with 100 percent placement": [50, "Low"],
  "data science course with 100 placement": [50, "High"],
  "data science course with 100 placement guarantee": [50, "High"],
  "data science course with guaranteed placement": [50, "High"],
  "data science course with placement": [500, "Medium"],
  "data science course with placement assistance": [50, "Medium"],
  "data science course with placement guarantee": [500, "Medium"],
  "data science guaranteed job": [50, "Low"],
  "data science guaranteed placement": [50, "High"],
  "data science job guarantee": [50, "Low"],
  "data science job guarantee course": [50, "Medium"],
  "data science job guarantee program": [50, "Medium"],
  "data science job guarantee training": [50, "Unknown"],
  "data science job placement": [50, "Low"],
  "data science online course with job guarantee": [50, "Low"],
  "data science online course with placement": [50, "High"],
  "data science online course with placement support": [50, "Unknown"],
  "data science online courses with placement": [50, "High"],
  "data science placement assistance": [50, "Low"],
  "data science placement course": [50, "High"],
  "data science placement guarantee": [50, "High"],
  "data science placement program": [50, "Unknown"],
  "data science program with job guarantee": [50, "Medium"],
  "data science program with placement": [50, "Unknown"],
  "data science training & placement": [50, "Unknown"],
  "data science training and job placement": [50, "Unknown"],
  "data science training and placement": [500, "High"],
  "data science training and placement near me": [50, "Unknown"],
  "data science training with job guarantee": [50, "High"],
  "data science training with job placement": [50, "Unknown"],
  "data science training with placement": [500, "High"],
  "data science with 100 placement": [50, "Unknown"],
  "data science with job guarantee": [50, "High"],
  "data science with placement guarantee": [50, "High"],
  "data scientist course with job guarantee": [50, "Medium"],
  "data scientist course with job placement": [50, "Low"],
  "data scientist course with placement": [500, "Medium"],
  "data scientist training and placement": [500, "High"],
  "developing bespoke software": [50, "Medium"],
  "development company software": [5000, "Low"],
  "digital agency for small business": [50, "Low"],
  "digital agency small": [50, "Unknown"],
  "digital marketing agency for small business": [500, "Low"],
  "digital marketing agency for small business near me": [50, "High"],
  "digital marketing agency for sme": [50, "Low"],
  "digital marketing companies for small business": [500, "Low"],
  "digital marketing company for small business": [500, "Low"],
  "digital marketing firm for small business": [50, "Unknown"],
  "digital marketing for sme": [50, "Low"],
  "digital marketing services for small business": [500, "Low"],
  "digital marketing small agency": [50, "Low"],
  "digital marketing solutions for small businesses": [50, "Low"],
  "enterprise custom software": [50, "Unknown"],
  "enterprise custom software development": [50, "Low"],
  "guaranteed placement data science": [50, "Unknown"],
  "internet marketing company for small business": [50, "Medium"],
  "internet marketing services for local businesses": [50, "Unknown"],
  "internet marketing services for small businesses": [50, "Low"],
  "job guarantee course in data science": [50, "High"],
  "job guarantee courses data science": [50, "High"],
  "job guarantee data science courses": [50, "Medium"],
  "job guarantee program data science": [50, "Low"],
  "job guaranteed data science course": [50, "Medium"],
  "local business marketing agency": [50, "Low"],
  "marketing agency for local businesses": [50, "Low"],
  "marketing agency for small business": [500, "Medium"],
  "marketing agency for sme": [50, "Medium"],
  "marketing companies for small business near me": [50, "Unknown"],
  "marketing company for small business": [50, "Low"],
  "marketing firms for small business": [50, "Low"],
  "online advertising agency for small business": [50, "Unknown"],
  "online data science course with job guarantee": [50, "Low"],
  "online data science course with placement": [50, "Medium"],
  "online data science course with placement guarantee": [50, "High"],
  "online marketing companies for small businesses": [50, "Low"],
  "online marketing services for small businesses": [50, "Low"],
  "outsourcing custom software": [50, "Unknown"],
  "outsourcing custom software development": [50, "Low"],
  "placement assistance data science": [50, "High"],
  "placement guarantee data science": [50, "Unknown"],
  "python and sql and agentic ai course online": [null, "Unknown"],
  "small business digital marketing firm": [500, "Low"],
  "small business digital marketing services": [500, "Low"],
  "small business internet marketing agency": [0, "Unknown"],
  "small business internet marketing company": [50, "Medium"],
  "small business marketing firms near me": [50, "Unknown"],
  "small business online marketing agency": [0, "Unknown"],
  "small business online marketing digital agency": [50, "Unknown"],
  "small digital agency": [50, "Unknown"],
  "small digital marketing agency": [50, "Medium"],
  "small digital marketing companies": [50, "Low"],
  "small digital marketing company": [50, "Low"],
  "small marketing agencies": [50, "Low"],
  "small social media marketing agency": [50, "High"],
  "smb marketing agency": [50, "Low"],
  "sme digital marketing agency": [50, "Low"],
  "social media agency for small businesses": [50, "Low"],
  "social media marketing agency for small business": [500, "Low"],
  "social media marketing agency small business": [50, "Low"],
  "social media marketing companies for small business": [500, "Low"],
  "software bespoke": [500, "Low"],
  "software bespoke company": [50, "Low"],
  "software development company": [5000, "Low"],
  "software development custom": [50, "Low"],
  "software development custom services": [0, "Unknown"],
  "top custom software companies": [50, "Low"],
  "top custom software developer": [50, "Unknown"],
  "top custom software development": [50, "High"],
  "top custom software development companies": [500, "Low"],
  "top digital marketing companies for small businesses": [50, "Low"],
};

const RANGES: [number, string][] = [
  [50, "10–100"],
  [500, "100–1K"],
  [5000, "1K–10K"],
  [50000, "10K–100K"],
  [500000, "100K–1M"],
];

/** "1K–10K a month · Low competition", or what is missing. */
export function keywordStats(keyword: string): string {
  const hit = KEYWORD_STATS[keyword.trim().toLowerCase()];
  if (!hit) return "Not in the planner file";
  const [volume, competition] = hit;
  const range = volume === null ? null : RANGES.find(([v]) => volume <= v)?.[1];
  return [
    range ? `${range} a month` : "Volume not given",
    competition && competition !== "Unknown"
      ? `${competition} competition`
      : "Competition not known",
  ].join(" · ");
}
