/**
 * Deciding whether a Python answer is right.
 *
 * The comparison rule is part of the problem, not a detail. A plain `===`
 * marks correct answers wrong on half of this sheet: Two Sum may return its
 * two indices either way round, 3Sum's triples are a set of sets, and the
 * in-place problems return nothing at all and mutate their argument. A judge
 * that fails a correct solution is worse than no judge, because a student has
 * no way to argue with it.
 *
 * Expectations are generated by running reference solutions
 * (scripts/build-python-tests.py) and served from /python-tests.json, so
 * nothing here is a value somebody typed out by hand.
 */

export type Compare =
  | { kind: "exact" }
  | { kind: "sorted" }
  | { kind: "unordered_nested" }
  | { kind: "inplace"; arg: number }
  | { kind: "k_prefix"; arg: number };

export type Case = { args: unknown[]; expect: unknown };

export type JudgedProblem = {
  slug: string;
  entry_point: string;
  starter_code: string;
  solution_py: string;
  note: string;
  tests: { compare: Compare; cases: Case[] };
};

/** Structural equality over the JSON shapes Python hands back. */
function deepEqual(a: unknown, b: unknown): boolean {
  if (a === b) return true;

  if (Array.isArray(a) && Array.isArray(b)) {
    return a.length === b.length && a.every((v, i) => deepEqual(v, b[i]));
  }

  if (
    typeof a === "object" &&
    typeof b === "object" &&
    a !== null &&
    b !== null
  ) {
    const left = a as Record<string, unknown>;
    const right = b as Record<string, unknown>;
    const keys = Object.keys(left);
    return (
      keys.length === Object.keys(right).length &&
      keys.every((k) => deepEqual(left[k], right[k]))
    );
  }

  return false;
}

/** A stable ordering for values whose order was never part of the answer. */
const byShape = (a: unknown, b: unknown) =>
  JSON.stringify(a) < JSON.stringify(b) ? -1 : 1;

function normalise(value: unknown, compare: Compare): unknown {
  if (compare.kind === "sorted" && Array.isArray(value)) {
    return [...value].sort(byShape);
  }

  if (compare.kind === "unordered_nested" && Array.isArray(value)) {
    return value
      .map((inner) => (Array.isArray(inner) ? [...inner].sort(byShape) : inner))
      .sort(byShape);
  }

  return value;
}

export function isCorrect(
  got: unknown,
  expect: unknown,
  compare: Compare,
): boolean {
  return deepEqual(normalise(got, compare), normalise(expect, compare));
}

/** How a value is shown back to the student — Python spelling, not JSON. */
export function display(value: unknown): string {
  if (value === null) return "None";
  if (value === true) return "True";
  if (value === false) return "False";
  if (typeof value === "string") return JSON.stringify(value);
  if (Array.isArray(value)) return `[${value.map(display).join(", ")}]`;
  if (typeof value === "object") {
    const entries = Object.entries(value as Record<string, unknown>);
    return `{${entries.map(([k, v]) => `${JSON.stringify(k)}: ${display(v)}`).join(", ")}}`;
  }
  return String(value);
}

/** The problem's arguments, written the way the call would look in Python. */
export function displayArgs(args: unknown[]): string {
  return args.map(display).join(", ");
}
