/**
 * The price book: what the services we build on cost, as a set of
 * spreadsheet-style tables. Generated from the team's research workbook
 * (AI_Infra_Pricing_Research.xlsx, prices checked on CHECKED), so a number
 * here is the workbook's number. Columns the workbook worked out in rupees
 * from dollars are left out: each money cell keeps the currency it was
 * quoted in, and the page converts at FX_INR_PER_USD.
 *
 * Confidence is the workbook's: "Official" is the vendor's own pricing
 * page, "Secondary" a third-party source, "Low" inferred or conflicting.
 */

export type Money = { usd: number } | { inr: number };
const usd = (amount: number): Money => ({ usd: amount });
const inr = (amount: number): Money => ({ inr: amount });

/** One cell. A string in a money or number column is a word like "Custom". */
export type Cell = string | number | Money | null;

export type Column = {
  label: string;
  /**
   * text: short words; long: a sentence or more (wraps wide); money: a
   * price; number: a count or size (with `unit`); percent: a fraction
   * shown as %; confidence: Official / Secondary / Low.
   */
  kind: "text" | "long" | "money" | "number" | "percent" | "confidence";
  unit?: string;
  /** Offer a filter of this column's values above the table. */
  facet?: boolean;
};

export type PriceRow = {
  /** Stable across edits: "w3" for the workbook's fourth row, a uuid for added ones. */
  id: string;
  /** In column order. */
  cells: Cell[];
  /** Where the row's name links to (our provider pages). */
  href?: string;
};

export type PriceTable = {
  id: string;
  title: string;
  note?: string;
  /** Whether rows can be ticked and set side by side. */
  compare: boolean;
  /** The columns that together name a row (for the comparison's headings). */
  nameColumns: number[];
  columns: Column[];
  rows: PriceRow[];
  /** Set when the team has changed this table from the workbook. */
  edited?: { at: string; by: string };
};

export type Sheet = {
  slug: string;
  title: string;
  lede: string;
  tables: PriceTable[];
  /** Prices the workbook says to confirm before relying on them. */
  checks: string[];
  sources: { label: string; url: string }[];
};

/** A sheet as generated from the workbook, rows still as plain cell lists. */
type WorkbookSheet = Omit<Sheet, "tables"> & {
  tables: (Omit<PriceTable, "rows"> & { rows: Cell[][] })[];
};

export const FX_INR_PER_USD = 96.43;
export const CHECKED = "6 Oct 2026";

const WORKBOOK: WorkbookSheet[] = [
  {
    slug: "ai-models",
    title: "AI models",
    lede: "API prices per 1M tokens for the main providers and open-source models, image and video models per image and per second, what it takes to run the open ones yourself, and when that starts to pay.",
    tables: [
      {
        id: "api",
        title: "API prices (per 1M tokens, standard tier, text)",
        note: "Tip: filter the Tier column to compare 'Cheap' vs 'Best' across providers. Batch APIs are ~50% cheaper at every major provider.",
        compare: true,
        nameColumns: [0],
        columns: [
          { label: "Model", kind: "text" },
          { label: "Provider", kind: "text", facet: true },
          { label: "Tier", kind: "text", facet: true },
          { label: "Input / 1M", kind: "money" },
          { label: "Output / 1M", kind: "money" },
          { label: "1M in + 1M out", kind: "money" },
          { label: "Confidence", kind: "confidence", facet: true },
          { label: "Licence", kind: "text" },
          { label: "GPUs to self-host", kind: "text" },
          { label: "Notes", kind: "long" },
        ],
        rows: [
          [
            "GPT-5.6 Luna",
            "OpenAI",
            "Cheap",
            usd(0.2),
            usd(1.2),
            usd(1.4),
            "Official",
            "Proprietary - API only",
            "Not self-hostable",
            "Fast, affordable. Cached input $0.02.",
          ],
          [
            "GPT-5.6 Terra",
            "OpenAI",
            "Mid",
            usd(2),
            usd(12),
            usd(14),
            "Official",
            "Proprietary - API only",
            "Not self-hostable",
            "Balanced, high-volume. Cached input $0.20.",
          ],
          [
            "GPT-5.6 Sol",
            "OpenAI",
            "Best",
            usd(5),
            usd(30),
            usd(35),
            "Official",
            "Proprietary - API only",
            "Not self-hostable",
            "Flagship (list price). Dev docs reportedly show $4/$20 promo to 21 Nov 2026.",
          ],
          [
            "GPT-6 Luna",
            "OpenAI",
            "Cheap",
            usd(0.1),
            usd(0.5),
            usd(0.6),
            "Low",
            "Proprietary - API only",
            "Not self-hostable",
            "Inferred from third-party price range; not on official page fetched. Verify.",
          ],
          [
            "GPT-6 Astra",
            "OpenAI",
            "Best",
            usd(10),
            usd(50),
            usd(60),
            "Secondary",
            "Proprietary - API only",
            "Not self-hostable",
            "Reported release 3 Sep 2026; third-party only. Verify. Batch -50%.",
          ],
          [
            "GPT-5 nano",
            "OpenAI",
            "Cheap",
            usd(0.05),
            usd(0.4),
            usd(0.45),
            "Secondary",
            "Proprietary - API only",
            "Not self-hostable",
            "Older budget model; may be phased out.",
          ],
          [
            "Claude Haiku 3.5",
            "Claude",
            "Cheap",
            usd(0.8),
            usd(4),
            usd(4.8),
            "Official",
            "Proprietary - API only",
            "Not self-hostable",
            "Legacy. Batch $0.40/$2.",
          ],
          [
            "Claude Haiku 4.5",
            "Claude",
            "Cheap",
            usd(1),
            usd(5),
            usd(6),
            "Official",
            "Proprietary - API only",
            "Not self-hostable",
            "Fast, near-frontier. Batch $0.50/$2.50.",
          ],
          [
            "Claude Sonnet 5.5",
            "Claude",
            "Mid",
            usd(2),
            usd(10),
            usd(12),
            "Official",
            "Proprietary - API only",
            "Not self-hostable",
            "Best speed/intelligence mix. Batch $1/$5.",
          ],
          [
            "Claude Opus 5.5",
            "Claude",
            "Best",
            usd(4),
            usd(20),
            usd(24),
            "Official",
            "Proprietary - API only",
            "Not self-hostable",
            "Agentic coding / knowledge work. Cache hit $0.20.",
          ],
          [
            "Claude Opus 5",
            "Claude",
            "Best",
            usd(5),
            usd(25),
            usd(30),
            "Official",
            "Proprietary - API only",
            "Not self-hostable",
            "Previous Opus. 1M context at standard price.",
          ],
          [
            "Claude Fable 5.1",
            "Claude",
            "Best",
            usd(10),
            usd(50),
            usd(60),
            "Official",
            "Proprietary - API only",
            "Not self-hostable",
            "Top tier (Mythos 5.1 same price). Cache hit $0.25.",
          ],
          [
            "Gemini 3.1 Flash-Lite",
            "Gemini",
            "Cheap",
            usd(0.25),
            usd(1.5),
            usd(1.75),
            "Official",
            "Proprietary - API only",
            "Not self-hostable",
            "Cheapest current Gemini. Batch $0.125/$0.75.",
          ],
          [
            "Gemini 3.5 Flash-Lite",
            "Gemini",
            "Cheap",
            usd(0.3),
            usd(2.5),
            usd(2.8),
            "Official",
            "Proprietary - API only",
            "Not self-hostable",
            "High-volume agentic tasks. Batch $0.15/$1.25.",
          ],
          [
            "Gemini 3.8 Flash",
            "Gemini",
            "Mid",
            usd(0.75),
            usd(3.75),
            usd(4.5),
            "Official",
            "Proprietary - API only",
            "Not self-hostable",
            "Prices double on 1 Jan 2027 ($1.50/$7.50).",
          ],
          [
            "Gemini 3.5 Flash",
            "Gemini",
            "Mid",
            usd(1.5),
            usd(9),
            usd(10.5),
            "Official",
            "Proprietary - API only",
            "Not self-hostable",
            "Earlier Flash; priced above 3.8 Flash.",
          ],
          [
            "Gemini 2.5 Pro",
            "Gemini",
            "Mid",
            usd(1.25),
            usd(10),
            usd(11.25),
            "Official",
            "Proprietary - API only",
            "Not self-hostable",
            "<=200K prompt. >200K: $2.50/$15.",
          ],
          [
            "Gemini 3.1 Pro Preview",
            "Gemini",
            "Best",
            usd(2),
            usd(12),
            usd(14),
            "Official",
            "Proprietary - API only",
            "Not self-hostable",
            "<=200K prompt. >200K: $4/$18.",
          ],
          [
            "Gemini 4 Argon (intro price)",
            "Gemini",
            "Best",
            usd(2),
            usd(10),
            usd(12),
            "Secondary",
            "Proprietary - API only",
            "Not self-hostable",
            "Not generally available: limited to trusted cyber defenders. Intro price $2/$10; list $4/$20 planned. Verify.",
          ],
          [
            "GLM-4.7-Flash (Z.ai)",
            "Open source",
            "Cheap",
            usd(0),
            usd(0),
            usd(0),
            "Official",
            "MIT - commercial OK",
            "1x H100 80GB (BF16)",
            "Free tier via Z.ai API; rate-limited. 30B total / 3B active.",
          ],
          [
            "gpt-oss-120b (OpenAI)",
            "Open source",
            "Cheap",
            usd(0.09),
            usd(0.6),
            usd(0.69),
            "Secondary",
            "Apache 2.0 - commercial OK",
            "1x H100 80GB",
            "Median of 24 hosting providers; cheapest is about $0.03 / $0.17. 117B total / 5B active.",
          ],
          [
            "Qwen3.8-27B (Alibaba)",
            "Open source",
            "Cheap",
            usd(0.04),
            usd(0.3),
            usd(0.34),
            "Secondary",
            "Apache 2.0 - commercial OK",
            "1x H100 80GB (BF16)",
            "Cheapest of 13 providers; others charge more. 27B dense, vision, 256K context.",
          ],
          [
            "GLM-5.3-Flash (Z.ai)",
            "Open source",
            "Cheap",
            usd(0.15),
            usd(0.5),
            usd(0.65),
            "Official",
            "MIT - commercial OK",
            "8x H100 80GB (FP8)",
            "Cached input $0.03. 320B total / 18B active.",
          ],
          [
            "DeepSeek V4.1-Flash",
            "Open source",
            "Cheap",
            usd(0.3),
            usd(1.2),
            usd(1.5),
            "Official",
            "MIT - commercial OK, no limits",
            "2x H200 (FP4+FP8)",
            "Peak price. Off-peak half ($0.15/$0.60). 284B total / 13B active (V4 Flash spec).",
          ],
          [
            "DeepSeek V4-Pro-0813",
            "Open source",
            "Best",
            usd(1.32),
            usd(3.96),
            usd(5.28),
            "Official",
            "MIT - commercial OK, no limits",
            "8x H200 (FP4+FP8)",
            "Peak price. Off-peak half ($0.66/$1.98). 1M context. 1.6T total / 49B active.",
          ],
          [
            "GLM-5.3 / GLM-5.2 (Z.ai)",
            "Open source",
            "Best",
            usd(1.4),
            usd(4.4),
            usd(5.8),
            "Official",
            "5.2 MIT; 5.3 custom - commercial OK*",
            "8x H200 (FP8)",
            "Long-horizon engineering model. About 744B total / 40B active.",
          ],
          [
            "Kimi K3 (Moonshot)",
            "Open source",
            "Best",
            usd(3),
            usd(15),
            usd(18),
            "Secondary",
            "Modified MIT - commercial OK*",
            "8x B300 (MXFP4)",
            "2.8T total / 104B active, open weights (26 Jul 2026); vision. Two third-party sources agree.",
          ],
        ],
      },
      {
        id: "image",
        title: "Image models (per image)",
        note: "Checked 10 Oct 2026 on each vendor's pricing page (not from the workbook). Standard is the setting most work uses; top is the biggest size or best quality the vendor prices. Prompt text and reference images can add a little. Google and OpenAI batch APIs are about half price.",
        compare: true,
        nameColumns: [0],
        columns: [
          { label: "Model", kind: "text" },
          { label: "Provider", kind: "text", facet: true },
          { label: "Tier", kind: "text", facet: true },
          { label: "Standard image", kind: "money" },
          { label: "Standard means", kind: "text" },
          { label: "Top setting", kind: "money" },
          { label: "Top means", kind: "text" },
          { label: "Confidence", kind: "confidence", facet: true },
          { label: "Notes", kind: "long" },
        ],
        rows: [
          [
            "Nano Banana 2.1",
            "Google",
            "Cheap",
            usd(0.0336),
            "1K",
            usd(0.113),
            "4K",
            "Official",
            "gemini-nano-banana-2.1. 2K $0.0504. Batch half price.",
          ],
          [
            "Nano Banana 2 Lite",
            "Google",
            "Cheap",
            usd(0.0336),
            "1K",
            null,
            null,
            "Official",
            "gemini-3.1-flash-lite-image. 1K only. Batch $0.0168.",
          ],
          [
            "Nano Banana 2",
            "Google",
            "Mid",
            usd(0.067),
            "1K",
            usd(0.151),
            "4K",
            "Official",
            "gemini-3.1-flash-image. 512px $0.045, 2K $0.101. Batch half price.",
          ],
          [
            "Nano Banana Pro",
            "Google",
            "Best",
            usd(0.134),
            "1K or 2K",
            usd(0.24),
            "4K",
            "Official",
            "gemini-3-pro-image. Batch $0.067 (1K/2K) and $0.12 (4K).",
          ],
          [
            "GPT Image 1 Mini",
            "OpenAI",
            "Cheap",
            usd(0.011),
            "Medium, 1024px",
            usd(0.036),
            "High, 1024px",
            "Official",
            "Low quality $0.005.",
          ],
          [
            "GPT Image 1.5",
            "OpenAI",
            "Mid",
            usd(0.034),
            "Medium, 1024px",
            usd(0.133),
            "High, 1024px",
            "Official",
            "Portrait or landscape (1024x1536) costs about 1.5x.",
          ],
          [
            "GPT Image 2",
            "OpenAI",
            "Mid",
            usd(0.053),
            "Medium, 1024px",
            usd(0.211),
            "High, 1024px",
            "Official",
            "Low quality $0.006. Portrait or landscape is a little cheaper ($0.041 medium).",
          ],
          [
            "GPT Image 2.5 Flare",
            "OpenAI via Runway",
            "Best",
            usd(0.05),
            "Medium, 1K",
            usd(0.63),
            "Max, 1K",
            "Secondary",
            "OpenAI lists only token prices ($30 per 1M image output tokens). These are Runway's credit prices: low $0.01, high $0.16, xhigh $0.28.",
          ],
          [
            "FLUX 3 Image",
            "Black Forest Labs",
            "Best",
            usd(0.048),
            "1K",
            usd(0.607),
            "4K",
            "Official",
            "768px $0.041, 2K $0.10.",
          ],
          [
            "FLUX.2 [max]",
            "Black Forest Labs",
            "Best",
            usd(0.07),
            "From, 1MP",
            null,
            null,
            "Official",
            "Bigger images cost more per extra megapixel.",
          ],
          [
            "FLUX.2 [pro]",
            "Black Forest Labs",
            "Mid",
            usd(0.03),
            "From, 1MP",
            null,
            null,
            "Official",
            "Editing from $0.045. Bigger images cost more per extra megapixel.",
          ],
          [
            "FLUX.2 [klein] 4B",
            "Black Forest Labs",
            "Cheap",
            usd(0.014),
            "1MP",
            null,
            null,
            "Official",
            "About $0.001 per extra megapixel.",
          ],
          [
            "Grok Imagine Image",
            "xAI",
            "Cheap",
            usd(0.02),
            "Any size",
            usd(0.05),
            "Quality model",
            "Official",
            "grok-imagine-image; the quality model is grok-imagine-image-quality.",
          ],
          [
            "Grok Imagine Image 2.0",
            "xAI",
            "Mid",
            usd(0.04),
            "Any size",
            null,
            null,
            "Official",
            "grok-imagine-image-2.0.",
          ],
          [
            "Seedream 5 Pro",
            "ByteDance via Runway",
            "Mid",
            usd(0.05),
            "1K",
            usd(0.09),
            "2K",
            "Secondary",
            "Runway's credit price. Seedream 5 Lite is $0.04 at any size.",
          ],
        ],
      },
      {
        id: "video",
        title: "Video models (per second of video)",
        note: "Checked 10 Oct 2026 on each vendor's pricing page (not from the workbook). An 8-second clip costs 8x the per-second price. Runway resells several makers' models at $0.01 a credit; those rows are Runway's prices.",
        compare: true,
        nameColumns: [0],
        columns: [
          { label: "Model", kind: "text" },
          { label: "Provider", kind: "text", facet: true },
          { label: "Tier", kind: "text", facet: true },
          { label: "720p / second", kind: "money" },
          { label: "1080p / second", kind: "money" },
          { label: "Sound", kind: "text" },
          { label: "Confidence", kind: "confidence", facet: true },
          { label: "Notes", kind: "long" },
        ],
        rows: [
          [
            "Veo 3.1 Lite",
            "Google",
            "Cheap",
            usd(0.05),
            usd(0.08),
            "Included",
            "Official",
            "veo-3.1-lite-generate-preview. No 4K. Charged only when the video generates.",
          ],
          [
            "Veo 3.1 Fast",
            "Google",
            "Mid",
            usd(0.1),
            usd(0.12),
            "Included",
            "Official",
            "veo-3.1-fast-generate-preview. 4K $0.30 a second.",
          ],
          [
            "Veo 3.1",
            "Google",
            "Best",
            usd(0.4),
            usd(0.4),
            "Included",
            "Official",
            "veo-3.1-generate-preview. 4K $0.60 a second.",
          ],
          [
            "Gemini Omni Flash 1.1",
            "Google",
            "Mid",
            usd(0.1),
            null,
            null,
            "Official",
            "gemini-omni-1.1-flash. Billed by tokens: 5,792 per second of 720p at $17.50 per 1M, about $0.10 a second. Can also edit video.",
          ],
          [
            "Grok Imagine Video 1.5 Lite",
            "xAI",
            "Cheap",
            usd(0.02),
            null,
            null,
            "Official",
            "grok-imagine-video-1.5-lite. xAI quotes one rate and does not say which resolution.",
          ],
          [
            "Grok Imagine Video 1.5",
            "xAI",
            "Mid",
            usd(0.08),
            null,
            null,
            "Official",
            "grok-imagine-video-1.5. xAI quotes one rate and does not say which resolution.",
          ],
          [
            "Gen-4 Turbo",
            "Runway",
            "Cheap",
            usd(0.05),
            null,
            "None",
            "Official",
            "One rate for every resolution Runway offers.",
          ],
          [
            "Gen-4.5",
            "Runway",
            "Mid",
            usd(0.12),
            null,
            "None",
            "Official",
            "One rate for every resolution Runway offers.",
          ],
          [
            "Seedance 2 Mini",
            "ByteDance via Runway",
            "Cheap",
            usd(0.16),
            null,
            null,
            "Secondary",
            "Minimum charge $0.64 a video.",
          ],
          [
            "Seedance 2",
            "ByteDance via Runway",
            "Best",
            usd(0.36),
            usd(0.4),
            null,
            "Secondary",
            "4K $1.50 a second.",
          ],
          [
            "Wan 3",
            "Alibaba via Runway",
            "Cheap",
            usd(0.1),
            usd(0.2),
            null,
            "Secondary",
            "480p $0.05 a second.",
          ],
          [
            "Kling 3.0",
            "Kuaishou",
            "Mid",
            usd(0.084),
            null,
            "Extra",
            "Low",
            "Kling's own rate as resellers quote it; we could not open Kling's price page. Sound and 1080p cost more.",
          ],
        ],
      },
      {
        id: "self-host",
        title: "Self-hosting the open models (GPU rental, 24/7)",
        note: "GPU rates are the cheapest on-demand marketplace prices (Spheron). AWS, Azure and GCP charge several times more. Cluster cost is for one replica running 24/7; add storage, networking and staff time. Self-hosting only beats the API when the GPUs stay busy. Compare the $ / month above with your monthly token spend from the API table. * Check the licence text before launch. Left out as not clearly commercial-friendly: Llama 4 (needs 'Built with Llama', EU limits on multimodal), Mistral Medium 3.5 (capped at $20M monthly revenue), Qwen3.8-Flash-Next (separate licence for hosted services), Codestral (no production use), and GLM-4.7-FlashX (no open weights found).",
        compare: true,
        nameColumns: [0],
        columns: [
          { label: "Model", kind: "text" },
          { label: "GPUs", kind: "number" },
          { label: "GPU type", kind: "text", facet: true },
          { label: "Per GPU-hour", kind: "money" },
          { label: "VRAM / GPU", kind: "number", unit: "GB" },
          { label: "Total VRAM", kind: "number", unit: "GB" },
          { label: "Cluster / hour", kind: "money" },
          { label: "Per month", kind: "money" },
          { label: "Sizing", kind: "long" },
          { label: "Licence", kind: "long" },
          { label: "GPU rate from", kind: "text" },
        ],
        rows: [
          [
            "GLM-4.7-Flash (Z.ai)",
            1,
            "H100",
            usd(2.65),
            80,
            80,
            usd(2.65),
            usd(1934.5),
            "30B total / 3B active. BF16 weights are about 60 GB (my estimate: 2 bytes per parameter), so it fits one 80GB card with limited KV cache. A 4-bit build should run on a 24GB RTX 4090 ($0.58/hr).",
            "MIT. Commercial use allowed.",
            "Spheron marketplace, 6 Oct 2026",
          ],
          [
            "gpt-oss-120b (OpenAI)",
            1,
            "H100",
            usd(2.65),
            80,
            80,
            usd(2.65),
            usd(1934.5),
            "117B total / 5B active. OpenAI built it to fit one 80GB GPU (H100 or MI300X).",
            "Apache 2.0. Commercial use allowed.",
            "Spheron marketplace, 6 Oct 2026",
          ],
          [
            "Qwen3.8-27B (Alibaba)",
            1,
            "H100",
            usd(2.65),
            80,
            80,
            usd(2.65),
            usd(1934.5),
            "27B dense. BF16 weights about 54 GB (my estimate), so one 80GB card works; FP8 would halve that.",
            "Apache 2.0. Commercial use allowed.",
            "Spheron marketplace, 6 Oct 2026",
          ],
          [
            "GLM-5.3-Flash (Z.ai)",
            8,
            "H100",
            usd(2.65),
            80,
            640,
            usd(21.2),
            usd(15476),
            "320B total / 18B active. FP8 weights about 306 GiB; two H200s do not fit. 8x H100 is the minimum, 8x H200 preferred for the full 1M context.",
            "MIT. Commercial use allowed.",
            "Spheron marketplace, 6 Oct 2026",
          ],
          [
            "DeepSeek V4.1-Flash",
            2,
            "H200",
            usd(5.51),
            141,
            282,
            usd(11.02),
            usd(8044.6),
            "284B total / 13B active (V4 Flash spec; V4.1 assumed the same). Native FP4+FP8 weights about 160 GB, so 2x H200 is the recommended target. FP8 needs about 320 GB (4x A100 80GB).",
            "MIT. Commercial use allowed, no usage caps.",
            "Spheron marketplace, 6 Oct 2026",
          ],
          [
            "DeepSeek V4-Pro-0813",
            8,
            "H200",
            usd(5.51),
            141,
            1128,
            usd(44.08),
            usd(32178.4),
            "1.6T total / 49B active. Native FP4+FP8 weights about 862 GB, so 8x H200 (1,128 GB) is the minimum. It does not fit 8x H100.",
            "MIT. Commercial use allowed, no usage caps.",
            "Spheron marketplace, 6 Oct 2026",
          ],
          [
            "GLM-5.3 / GLM-5.2 (Z.ai)",
            8,
            "H200",
            usd(5.51),
            141,
            1128,
            usd(44.08),
            usd(32178.4),
            "About 744B total / 40B active. FP8 weights about 744 GB on 8x H200. An INT4 (AWQ) build is about 372 GB and runs on 4x H200 at half the cost.",
            "5.2: MIT. 5.3: custom licence, commercial OK, but a hosted-AI business above $10B revenue needs a Z.ai security review.",
            "Spheron marketplace, 6 Oct 2026",
          ],
          [
            "Kimi K3 (Moonshot)",
            8,
            "B300",
            usd(5.81),
            288,
            2304,
            usd(46.48),
            usd(33930.4),
            "2.8T total / 104B active. Native MXFP4 checkpoint is about 1.56 TB. One 8x B300 node is the best fit; alternatives are 16x H200/B200 or 32x H100. Rate shown is spot because no B300 on-demand rate was listed.",
            "Modified MIT. Commercial use allowed, with a Kimi K3 attribution condition above a revenue/user threshold (about $20M monthly revenue). Read the licence.",
            "Spheron marketplace, 6 Oct 2026",
          ],
        ],
      },
      {
        id: "versus",
        title: "APIs the self-host options are measured against",
        note: "Blended price assumes 85% of tokens are input (document-heavy work). Self-hosting wins only when the GPUs stay busy. Break-even = monthly GPU cost divided by the API price per 1M tokens. Below that volume, stay on the API. Quality is not compared here: open models trail Gemini 3.1 Pro on hard reasoning, so test on your own documents first.",
        compare: true,
        nameColumns: [0],
        columns: [
          { label: "API", kind: "text" },
          { label: "Input / 1M", kind: "money" },
          { label: "Output / 1M", kind: "money" },
          { label: "Blended / 1M", kind: "money" },
          { label: "Confidence", kind: "confidence" },
          { label: "Notes", kind: "long" },
        ],
        rows: [
          [
            "Gemini 3.1 Pro",
            usd(2),
            usd(12),
            usd(3.5),
            "Official",
            "Preview model: price and name can change.",
          ],
          [
            "Gemini 4 Argon (intro)",
            usd(2),
            usd(10),
            usd(3.2),
            "Secondary",
            "Limited access today (trusted cyber defenders); no public API date. Intro price has no stated end date.",
          ],
          [
            "Gemini 4 Argon (list)",
            usd(4),
            usd(20),
            usd(6.4),
            "Secondary",
            "Planned list price after the intro period.",
          ],
        ],
      },
      {
        id: "break-even",
        title: "Break-even: when your own GPUs beat the API",
        note: "Example: 1,000 M tokens a month is about 1 billion tokens, or roughly 380 tokens a second around the clock. A busy office-hours app often averages far less, so check your real traffic before renting.",
        compare: true,
        nameColumns: [0],
        columns: [
          { label: "Model", kind: "text" },
          { label: "GPUs", kind: "text" },
          { label: "Cluster / month", kind: "money" },
          { label: "With 1 replica and $1,500 ops / month", kind: "money" },
          {
            label: "Break-even vs Gemini 3.1 Pro",
            kind: "number",
            unit: "M tokens / month",
          },
          {
            label: "vs Gemini 4 intro",
            kind: "number",
            unit: "M tokens / month",
          },
          {
            label: "vs Gemini 4 list",
            kind: "number",
            unit: "M tokens / month",
          },
          { label: "Tokens / sec at break-even", kind: "number" },
        ],
        rows: [
          [
            "GLM-4.7-Flash (Z.ai)",
            "1x H100",
            usd(1934.5),
            usd(3434.5),
            981.285714,
            1073.28125,
            536.640625,
            373.396391,
          ],
          [
            "gpt-oss-120b (OpenAI)",
            "1x H100",
            usd(1934.5),
            usd(3434.5),
            981.285714,
            1073.28125,
            536.640625,
            373.396391,
          ],
          [
            "Qwen3.8-27B (Alibaba)",
            "1x H100",
            usd(1934.5),
            usd(3434.5),
            981.285714,
            1073.28125,
            536.640625,
            373.396391,
          ],
          [
            "GLM-5.3-Flash (Z.ai)",
            "8x H100",
            usd(15476),
            usd(16976),
            4850.285714,
            5305,
            2652.5,
            1845.618613,
          ],
          [
            "DeepSeek V4.1-Flash",
            "2x H200",
            usd(8044.6),
            usd(9544.6),
            2727.028571,
            2982.6875,
            1491.34375,
            1037.682105,
          ],
          [
            "DeepSeek V4-Pro-0813",
            "8x H200",
            usd(32178.4),
            usd(33678.4),
            9622.4,
            10524.5,
            5262.25,
            3661.491629,
          ],
          [
            "GLM-5.3 / GLM-5.2 (Z.ai)",
            "8x H200",
            usd(32178.4),
            usd(33678.4),
            9622.4,
            10524.5,
            5262.25,
            3661.491629,
          ],
          [
            "Kimi K3 (Moonshot)",
            "8x B300",
            usd(33930.4),
            usd(35430.4),
            10122.971429,
            11072,
            5536,
            3851.967819,
          ],
        ],
      },
      {
        id: "switch",
        title: "When to switch from the API",
        compare: false,
        nameColumns: [0],
        columns: [
          { label: "Step", kind: "text" },
          { label: "What it means", kind: "long" },
        ],
        rows: [
          [
            "1. Stay on the API first",
            "Until your monthly AI bill passes about 2x the cost of one GPU server plus ops, and the load is steady. Below that, API prices per token are lower than idle GPUs.",
          ],
          [
            "2. Cut API cost before leaving it",
            "Use batch mode (about 50% cheaper), prompt caching (Gemini 4 cached input is $0.10 vs $2), and a Flash-Lite model for bulk steps. Often saves more than self-hosting.",
          ],
          [
            "3. Try a hosted open model next",
            "gpt-oss-120b, DeepSeek or GLM through an API at $0.09-$1.40 input per 1M tokens, with no servers to run. Check quality on Kannada legal documents.",
          ],
          [
            "4. Rent GPUs when all of these are true",
            "Monthly volume is above the break-even in the table, traffic is steady (40%+ busy), an open model passes your accuracy tests, and someone owns uptime.",
          ],
        ],
      },
    ],
    checks: [
      "OpenAI: official page shows GPT-5.6 Luna/Terra/Sol. GPT-6 Astra ($10/$50) appears only in third-party sources dated Sep-Oct 2026; GPT-6 Luna price is inferred from a stated range. Sol also has conflicting list vs docs price ($5/$30 vs $4/$20 promo to 21 Nov 2026).",
      "Gemini 3.8 / 3.7 / 3.6 Flash prices double on 1 Jan 2027 ($1.50 in / $7.50 out).",
      "DeepSeek is cheaper off-peak (half price outside 01-04 and 06-10 UTC on weekdays). The sheet lists the peak price.",
      "OpenAI removed the Sora video API on 24 Sep 2026, so it is not listed. gpt-image-1 shuts down on 23 Oct 2026, and Google's first Nano Banana (gemini-2.5-flash-image) shut down on 2 Oct 2026.",
      "Kling's video price comes from resellers quoting Kling's rate. Check klingai.com before quoting it.",
    ],
    sources: [
      {
        label: "Claude pricing",
        url: "https://platform.claude.com/docs/en/about-claude/pricing",
      },
      {
        label: "Gemini pricing (text, image, Veo)",
        url: "https://ai.google.dev/gemini-api/docs/pricing",
      },
      { label: "OpenAI pricing", url: "https://openai.com/api/pricing" },
      {
        label: "OpenAI GPT-6 (third-party)",
        url: "https://axis-intelligence.com/openai-api-pricing/",
      },
      {
        label: "DeepSeek pricing",
        url: "https://api-docs.deepseek.com/quick_start/pricing",
      },
      {
        label: "Z.ai (GLM) pricing",
        url: "https://docs.z.ai/guides/overview/pricing",
      },
      {
        label: "Kimi K3 pricing (third-party)",
        url: "https://devtk.ai/en/blog/kimi-k3-vs-glm-5-2-deepseek-v4-2026/",
      },
      {
        label: "Gemini 4 Argon pricing (third-party)",
        url: "https://www.aipricing.guru/news/google-gemini-4-argon-pricing-access-october-2026/",
      },
      {
        label: "Self-host vs API break-even",
        url: "https://cohorte.co/blog/self-hosted-llm-cost-vs-api-break-even",
      },
      {
        label: "GPU rates (Spheron)",
        url: "https://www.spheron.network/pricing/",
      },
      {
        label: "GLM-5.3 GPU sizing",
        url: "https://www.spheron.network/blog/deploy-glm-5-3-gpu-cloud/",
      },
      {
        label: "GLM-5.2 GPU sizing",
        url: "https://www.spheron.network/blog/deploy-glm-5-2-gpu-cloud/",
      },
      {
        label: "GLM-5.3-Flash sizing",
        url: "https://www.yottalabs.ai/post/glm-5-3-flash-hardware-requirements-gpu-memory-2026",
      },
      {
        label: "DeepSeek V4 sizing",
        url: "https://codersera.com/blog/deepseek-v4-vram-gpu-requirements-2026/",
      },
      {
        label: "DeepSeek V4 licence",
        url: "https://localaimaster.com/models/deepseek-v4",
      },
      {
        label: "Kimi K3 sizing",
        url: "https://www.spheron.network/blog/deploy-kimi-k3-gpu-cloud/",
      },
      {
        label: "Open LLM licences",
        url: "https://wz-it.com/en/knowledge/ki/open-llm-licenses-commercial-use/",
      },
      {
        label: "gpt-oss-120b specs and price",
        url: "https://infrabase.ai/models/gpt-oss-120b",
      },
      {
        label: "gpt-oss-120b price spread",
        url: "https://pricepertoken.com/pricing-page/model/openai-gpt-oss-120b",
      },
      {
        label: "Qwen3.8-27B specs and price",
        url: "https://infrabase.ai/models/qwen3-8-27b",
      },
      {
        label: "GPT Image per-image prices",
        url: "https://developers.openai.com/api/docs/guides/image-generation",
      },
      {
        label: "OpenAI deprecations (Sora, gpt-image-1)",
        url: "https://developers.openai.com/api/docs/deprecations",
      },
      { label: "FLUX pricing", url: "https://docs.bfl.ai/quick_start/pricing" },
      {
        label: "xAI Grok Imagine pricing",
        url: "https://docs.x.ai/docs/models",
      },
      {
        label: "Runway API credits",
        url: "https://docs.dev.runwayml.com/guides/pricing/",
      },
      {
        label: "Kling 3.0 price (reseller)",
        url: "https://evolink.ai/blog/kling-3-api-pricing-integration-guide",
      },
    ],
  },
  {
    slug: "deployment",
    title: "Deployment",
    lede: "AWS virtual machines and load balancer in Mumbai against Railway plans and usage rates.",
    tables: [
      {
        id: "ec2",
        title: "AWS EC2 on-demand, Linux, Mumbai (ap-south-1)",
        note: "Excludes EBS disk, data transfer out and public IPv4. Source: doit.com ap-south-1 table.",
        compare: true,
        nameColumns: [0],
        columns: [
          { label: "Instance", kind: "text" },
          { label: "vCPU", kind: "number" },
          { label: "RAM", kind: "number", unit: "GB" },
          { label: "Per hour", kind: "money" },
          { label: "Per month", kind: "money" },
          { label: "Notes", kind: "long" },
        ],
        rows: [
          [
            "t3.micro",
            2,
            1,
            usd(0.0112),
            usd(8.176),
            "Free-tier eligible (750 h/mo for new accounts)",
          ],
          ["t3.small", 2, 2, usd(0.0224), usd(16.352), "Small APIs / staging"],
          [
            "t3.medium",
            2,
            4,
            usd(0.0448),
            usd(32.704),
            "Common starter production VM",
          ],
          [
            "t3.large",
            2,
            8,
            usd(0.0896),
            usd(65.408),
            "Spot ~ $0.03/h (about 63% off)",
          ],
          ["t3.xlarge", 4, 16, usd(0.1792), usd(130.816), null],
        ],
      },
      {
        id: "alb",
        title: "AWS Application Load Balancer",
        note: "Data transfer out to internet is billed separately (about $0.09/GB after the first 100 GB/mo).",
        compare: true,
        nameColumns: [0],
        columns: [
          { label: "Item", kind: "text" },
          { label: "Unit", kind: "text" },
          { label: "Per hour", kind: "money" },
          { label: "Per month", kind: "money" },
          { label: "Notes", kind: "long" },
        ],
        rows: [
          [
            "ALB base charge",
            "per ALB-hour",
            usd(0.0225),
            usd(16.425),
            "Roughly $16.43/mo before any traffic",
          ],
          [
            "Capacity unit (LCU)",
            "per LCU-hour",
            usd(0.008),
            usd(5.84),
            "1 LCU ~ 1 GB/h processed; low traffic often needs 1 LCU",
          ],
          [
            "Public IPv4 address",
            "per IP-hour",
            usd(0.005),
            usd(3.65),
            "Billed under VPC pricing; ALB needs 2+ in multi-AZ",
          ],
        ],
      },
      {
        id: "railway-plans",
        title: "Railway plans",
        compare: true,
        nameColumns: [0],
        columns: [
          { label: "Plan", kind: "text" },
          { label: "Minimum / month", kind: "money" },
          { label: "Usage included", kind: "money" },
          { label: "Max per service", kind: "text" },
          { label: "Storage cap", kind: "text" },
          { label: "Replicas", kind: "text" },
          { label: "Notes", kind: "long" },
        ],
        rows: [
          [
            "Free",
            usd(0),
            usd(0),
            "1 vCPU / 0.5 GB",
            "0.5 GB",
            "1",
            "30-day trial with $5 credit, then about $1/mo. Community support.",
          ],
          [
            "Hobby",
            usd(5),
            usd(5),
            "48 vCPU / 48 GB",
            "5 GB",
            "up to 6",
            "Credit is not carried over. 99.9% availability target.",
          ],
          [
            "Pro",
            usd(20),
            usd(20),
            "1,000 vCPU / 1 TB",
            "1 TB",
            "up to 42",
            "Unlimited seats, 30-day logs, 99.99% target.",
          ],
          [
            "Enterprise",
            "Custom",
            null,
            "2,400 vCPU / 2.4 TB",
            "5 TB",
            "highest",
            "Custom pricing; SSO, HIPAA, dedicated VMs.",
          ],
        ],
      },
      {
        id: "railway-usage",
        title: "Railway usage rates (billed per second of use)",
        compare: true,
        nameColumns: [0],
        columns: [
          { label: "Resource", kind: "text" },
          { label: "Unit", kind: "text" },
          { label: "Rate", kind: "money" },
          { label: "Rate basis", kind: "text" },
          { label: "Per unit-month", kind: "money" },
          { label: "Notes", kind: "long" },
        ],
        rows: [
          [
            "Memory",
            "per GB",
            usd(4e-6),
            "per second",
            usd(10.14408),
            "Billed only for what the service uses",
          ],
          ["CPU", "per vCPU", usd(8e-6), "per second", usd(20.28816), null],
          [
            "Volume storage",
            "per GB",
            usd(0),
            "per second",
            usd(0.15768),
            "Persistent disk (databases etc.)",
          ],
          ["Network egress", "per GB", usd(0.05), "per GB", usd(0.05), null],
          [
            "Object storage (buckets)",
            "per GB",
            usd(0.015),
            "per GB-month",
            usd(0.015),
            "Free egress and free operations",
          ],
        ],
      },
      {
        id: "example",
        title: "Example always-on monthly cost",
        compare: true,
        nameColumns: [0],
        columns: [
          { label: "Scenario", kind: "text" },
          { label: "vCPU", kind: "number" },
          { label: "RAM", kind: "number", unit: "GB" },
          { label: "Disk", kind: "number", unit: "GB" },
          { label: "Traffic out", kind: "number", unit: "GB" },
          { label: "Per month", kind: "money" },
          { label: "How it is worked out", kind: "long" },
        ],
        rows: [
          [
            "Railway app (usage only)",
            1,
            2,
            10,
            100,
            usd(47.15312),
            "vCPU, RAM and disk at 24/7 full use (upper bound; idle apps cost less) + egress. Plan minimum is a floor, not an add-on.",
          ],
          [
            "Railway bill on Hobby",
            null,
            null,
            null,
            null,
            usd(47.15312),
            "Greater of the $5 minimum and usage (credit covers the first $5).",
          ],
          [
            "AWS t3.medium + ALB",
            2,
            4,
            30,
            100,
            usd(64.669),
            "t3.medium + ALB base + 1 LCU + 2 IPv4 + EBS at ~$0.08/GB-mo (assumed gp3, Mumbai approx.) + egress after 100 GB free.",
          ],
        ],
      },
      {
        id: "aws-vs-railway",
        title: "AWS against Railway, besides price",
        compare: false,
        nameColumns: [0],
        columns: [
          { label: "Factor", kind: "text" },
          { label: "AWS (EC2 + ALB)", kind: "long" },
          { label: "Railway", kind: "long" },
          { label: "Why it matters", kind: "long" },
        ],
        rows: [
          [
            "Billing",
            "Per hour for the whole VM, even if idle, plus ALB base cost.",
            "Per second for CPU, RAM, disk and egress actually used, above the plan minimum.",
            "Spiky or small apps cost far less on Railway; steady heavy load can favour AWS.",
          ],
          [
            "Setup effort",
            "You manage OS, patching, SSL, scaling and deploys.",
            "Push code or a Docker image; domain, SSL and deploys are handled.",
            "Railway saves engineering time; AWS gives full control.",
          ],
          [
            "Load balancer and scaling",
            "ALB is a separate paid item; autoscaling groups need setup.",
            "Replicas are set per service in the plan limits; no separate load balancer to buy.",
            "Check replica limits on your plan before relying on it.",
          ],
          [
            "India region",
            "Mumbai (ap-south-1) available.",
            "No India region. Nearest is Singapore; others are US and Amsterdam.",
            "Matters for latency to Indian users and data-residency rules.",
          ],
          [
            "Limits and ceiling",
            "Practically unlimited sizes and services.",
            "Per-service caps by plan (see section C).",
            "Very large workloads or GPUs outgrow Railway.",
          ],
        ],
      },
    ],
    checks: [
      "AWS: EC2 rates are Mumbai (ap-south-1) from a third-party tracker; ALB and S3 are published US-East list prices (the AWS page did not render numbers). Mumbai differs slightly.",
    ],
    sources: [
      { label: "Railway pricing", url: "https://railway.com/pricing" },
      {
        label: "EC2 Mumbai rates",
        url: "https://www.doit.com/compute/spot/ap-south-1/t3.large",
      },
      {
        label: "AWS ALB rates",
        url: "https://cloudburn.io/blog/aws-elastic-load-balancing-pricing",
      },
    ],
  },
  {
    slug: "storage",
    title: "Storage",
    lede: "Supabase database plans and add-ons, and file storage from Cloudflare R2, AWS S3, Supabase and Railway.",
    tables: [
      {
        id: "supabase",
        title: "Supabase plans",
        compare: true,
        nameColumns: [0],
        columns: [
          { label: "Plan", kind: "text" },
          { label: "Per month", kind: "money" },
          { label: "Database disk", kind: "text" },
          { label: "File storage", kind: "text" },
          { label: "Egress", kind: "text" },
          { label: "Monthly active users", kind: "text" },
          { label: "Notes", kind: "long" },
        ],
        rows: [
          [
            "Free",
            usd(0),
            "500 MB",
            "1 GB",
            "5 GB",
            "50,000",
            "Paused after 1 week idle; max 2 active projects; shared CPU.",
          ],
          [
            "Pro",
            usd(25),
            "8 GB per project",
            "100 GB",
            "250 GB",
            "100,000",
            "Includes $10/mo compute credit (covers one Micro). Daily backups 7 days. Spend cap on by default.",
          ],
          [
            "Team",
            usd(599),
            "8 GB per project",
            "100 GB",
            "250 GB",
            "100,000",
            "SOC2 / ISO 27001, SSO, 14-day backups, priority support.",
          ],
          [
            "Enterprise",
            "Custom",
            "Custom",
            "Custom",
            "Custom",
            "Custom",
            "Uptime SLA, PrivateLink, support manager.",
          ],
        ],
      },
      {
        id: "supabase-addons",
        title: "Supabase add-ons and overage",
        compare: true,
        nameColumns: [0],
        columns: [
          { label: "Item", kind: "text" },
          { label: "Price", kind: "money" },
          { label: "Unit", kind: "text" },
          { label: "Notes", kind: "long" },
        ],
        rows: [
          [
            "Compute - Micro (1 GB, shared)",
            usd(10),
            "per month",
            "Covered by the $10 credit on paid plans",
          ],
          ["Compute - Small (2 GB, shared)", usd(15), "per month", null],
          ["Compute - Medium (4 GB, shared)", usd(60), "per month", null],
          [
            "Compute - Large (8 GB, 2 vCPU dedicated)",
            usd(110),
            "per month",
            null,
          ],
          ["Compute - XL (16 GB, 4 vCPU)", usd(210), "per month", null],
          ["Compute - 2XL (32 GB, 8 vCPU)", usd(410), "per month", null],
          ["Extra database disk", usd(0.125), "per GB-month", "Beyond 8 GB"],
          ["Extra file storage", usd(0.0213), "per GB-month", "Beyond 100 GB"],
          [
            "Extra egress",
            usd(0.09),
            "per GB",
            "Beyond 250 GB; cached egress $0.03/GB",
          ],
          [
            "Extra monthly active users",
            usd(0.00325),
            "per MAU",
            "Beyond 100,000",
          ],
          [
            "Point-in-time recovery",
            usd(100),
            "per month",
            "Per 7 days of retention",
          ],
          ["Custom domain", usd(10), "per month", "Per project"],
          [
            "Additional project",
            usd(10),
            "per month",
            "Starting price, plus its compute",
          ],
        ],
      },
      {
        id: "files",
        title: "File and image storage",
        compare: true,
        nameColumns: [0],
        columns: [
          { label: "Service", kind: "text" },
          { label: "Storage / GB-month", kind: "money" },
          { label: "Writes / million", kind: "money" },
          { label: "Reads / million", kind: "money" },
          { label: "Egress / GB", kind: "money" },
          { label: "Free allowance", kind: "long" },
          { label: "Key differences", kind: "long" },
        ],
        rows: [
          [
            "Cloudflare R2 Standard",
            usd(0.015),
            usd(4.5),
            usd(0.36),
            usd(0),
            "10 GB, 1M writes, 10M reads free per month. Egress always free.",
            "Can serve public files on your own domain with CDN. Lifecycle rules. Best for public images.",
          ],
          [
            "Cloudflare R2 Infrequent Access",
            usd(0.01),
            usd(9),
            usd(0.9),
            usd(0),
            "Plus $0.01/GB retrieval; 30-day minimum. No free tier.",
            "Same features as Standard, but reads cost more. Use for old backups and archives only.",
          ],
          [
            "AWS S3 Standard (US-East list)",
            usd(0.023),
            usd(5),
            usd(0.4),
            usd(0.09),
            "100 GB/mo egress free (all AWS combined). PUT $0.005 / GET $0.0004 per 1,000. Mumbai about 10% higher.",
            "Most features (versioning, lifecycle, many classes). Paid egress. Best if the app already runs on AWS.",
          ],
          [
            "Supabase Storage (Pro)",
            usd(0.0213),
            usd(0),
            usd(0),
            usd(0.09),
            "100 GB and 250 GB egress included; no per-request charge; CDN cached egress $0.03/GB.",
            "Tied to Supabase auth and access rules; simplest if you already use Supabase. Includes CDN.",
          ],
          [
            "Railway Buckets",
            usd(0.015),
            usd(0),
            usd(0),
            usd(0),
            "Free operations and egress; max 1 TB on Hobby.",
            "Private only: no public URLs, use presigned links or your backend. No backups, versioning or lifecycle; deleted data gone after 52 hours. Fixed region.",
          ],
        ],
      },
      {
        id: "files-example",
        title:
          "Example bill: 500 GB stored, 1,000 GB egress, 1M writes and 20M reads a month",
        note: "Egress-heavy workloads (images/video) favour R2 or Railway; S3 wins only when you are already inside AWS.",
        compare: true,
        nameColumns: [0],
        columns: [
          { label: "Service", kind: "text" },
          { label: "Per month", kind: "money" },
          { label: "What the sum includes", kind: "long" },
        ],
        rows: [
          [
            "Cloudflare R2 Standard",
            usd(10.95),
            "Storage and operations after free tier; egress free.",
          ],
          [
            "AWS S3 Standard",
            usd(105.5),
            "Storage + requests + egress after 100 GB free.",
          ],
          [
            "Supabase Storage (add to $25 Pro)",
            usd(76.02),
            "Overage beyond Pro's 100 GB / 250 GB only; excludes the $25 plan.",
          ],
          [
            "Railway Buckets",
            usd(7.5),
            "Storage only; operations and egress free.",
          ],
        ],
      },
    ],
    checks: [
      "AWS: EC2 rates are Mumbai (ap-south-1) from a third-party tracker; ALB and S3 are published US-East list prices (the AWS page did not render numbers). Mumbai differs slightly.",
    ],
    sources: [
      { label: "Railway pricing", url: "https://railway.com/pricing" },
      { label: "Supabase pricing", url: "https://supabase.com/pricing" },
      {
        label: "Cloudflare R2 pricing",
        url: "https://developers.cloudflare.com/r2/pricing/",
      },
      { label: "AWS S3 pricing", url: "https://aws.amazon.com/s3/pricing/" },
    ],
  },
  {
    slug: "domains",
    title: "Domains",
    lede: "BigRock, GoDaddy and Hostinger for .com and .in: first year, renewal, and what three or five years really cost.",
    tables: [
      {
        id: "registrars",
        title: "Registrars (USD listings)",
        note: "Totals = best first-year price + renewals for the remaining years + yearly privacy and ICANN fees. Assumes you keep the name and renew at the standard rate.",
        compare: true,
        nameColumns: [0, 1],
        columns: [
          { label: "Registrar", kind: "text", facet: true },
          { label: "TLD", kind: "text", facet: true },
          { label: "Promo 1st year", kind: "money" },
          { label: "Regular 1st year", kind: "money" },
          { label: "Best 1st year", kind: "money" },
          { label: "Renewal / year", kind: "money" },
          { label: "Transfer", kind: "money" },
          { label: "Privacy / year", kind: "money" },
          { label: "ICANN fee / year", kind: "money" },
          { label: "3-year total", kind: "money" },
          { label: "5-year total", kind: "money" },
          { label: "Notes", kind: "long" },
        ],
        rows: [
          [
            "BigRock",
            ".com",
            null,
            usd(7.77),
            usd(7.77),
            usd(15.34),
            usd(10.05),
            usd(5.17),
            usd(0),
            usd(53.96),
            usd(94.98),
            "No promo needed. WHOIS privacy is a paid extra.",
          ],
          [
            "BigRock",
            ".in",
            null,
            usd(5.69),
            usd(5.69),
            usd(9.32),
            usd(8.8),
            usd(5.17),
            usd(0),
            usd(39.84),
            usd(68.82),
            "Cheapest renewal of the three for .in.",
          ],
          [
            "GoDaddy",
            ".com",
            usd(2.99),
            usd(12.99),
            usd(2.99),
            usd(22.99),
            usd(12.99),
            usd(0),
            usd(0.2),
            usd(49.57),
            usd(95.95),
            "Promo code GDWELCOME: new customers, limit 1. Renewal is the highest.",
          ],
          [
            "GoDaddy",
            ".in",
            usd(1.03),
            usd(12.99),
            usd(1.03),
            usd(12.99),
            usd(12.99),
            usd(0),
            usd(0.2),
            usd(27.61),
            usd(53.99),
            "Promo GOINDIA: new customers, limit 1. US listing; India site differs.",
          ],
          [
            "Hostinger",
            ".com",
            usd(8.49),
            usd(9.99),
            usd(8.49),
            usd(19.99),
            usd(9.99),
            usd(0),
            usd(0.2),
            usd(49.07),
            usd(89.45),
            "Promo TLDLIST15 (limit 1). Privacy free.",
          ],
          [
            "Hostinger",
            ".in",
            null,
            usd(6.99),
            usd(6.99),
            usd(9.99),
            null,
            usd(0),
            usd(0.2),
            usd(27.57),
            usd(47.95),
            "From a May 2026 snapshot; transfer price not listed. Lower confidence.",
          ],
        ],
      },
      {
        id: "india",
        title: "India-site offers (quoted in ₹)",
        compare: true,
        nameColumns: [0, 1],
        columns: [
          { label: "Registrar", kind: "text" },
          { label: "TLD", kind: "text" },
          { label: "1st year", kind: "money" },
          { label: "Renewal", kind: "money" },
          { label: "Notes", kind: "long" },
        ],
        rows: [
          [
            "Hostinger India",
            ".com",
            inr(1),
            inr(1499),
            "Page read 29 Aug 2026 (Zoutons). Teaser first-year price; renews at ₹1,499.",
          ],
          [
            "GoDaddy India",
            ".in / .co.in",
            inr(99),
            null,
            "Flash sale for Indian customers with an Indian address; renewal not stated (US list $12.99).",
          ],
        ],
      },
    ],
    checks: [
      "Domains: USD prices are DomainOffer's US listings (GoDaddy note: may differ by country). India-site INR offers are shown separately on the Domains sheet.",
    ],
    sources: [
      {
        label: "BigRock .com / .in",
        url: "https://domainoffer.net/tld/com/bigrock",
      },
      {
        label: "GoDaddy .com / .in",
        url: "https://domainoffer.net/tld/com/godaddy",
      },
      {
        label: "Hostinger .com / .in",
        url: "https://domainoffer.net/tld/com/hostinger",
      },
      {
        label: "Hostinger India (INR)",
        url: "https://zoutons.com/news/hostinger-domain-price-india-2026",
      },
    ],
  },
  {
    slug: "payments-delivery",
    title: "Payments & delivery",
    lede: "Indian payment gateway fees and courier rates. Fees exclude 18% GST on the fee unless stated.",
    tables: [
      {
        id: "gateways",
        title: "Payment gateway fees",
        compare: true,
        nameColumns: [0, 1],
        columns: [
          { label: "Provider", kind: "text", facet: true },
          { label: "Method", kind: "text" },
          { label: "Fee (low)", kind: "percent" },
          { label: "Fee (high)", kind: "percent" },
          { label: "Setup / AMC", kind: "text" },
          { label: "Confidence", kind: "confidence", facet: true },
          { label: "Notes", kind: "long" },
        ],
        rows: [
          [
            "Razorpay",
            "Domestic cards, netbanking, wallets",
            0.02,
            0.02,
            "None",
            "Official",
            "2% + 18% GST on the fee. Advertises 0% platform fee for first 90 days (terms apply).",
          ],
          [
            "Razorpay",
            "UPI",
            0.02,
            0.02,
            "None",
            "Official",
            "Zero bank MDR, but Razorpay FAQ states a 2% platform fee applies. Some blogs say 0% - verify.",
          ],
          [
            "Razorpay",
            "RuPay debit cards",
            0.02,
            0.02,
            "None",
            "Official",
            "Zero MDR; same 2% platform fee per FAQ.",
          ],
          [
            "Razorpay",
            "Credit card on UPI",
            0.0215,
            0.0215,
            "None",
            "Official",
            "2.15% + GST.",
          ],
          [
            "Razorpay",
            "International cards",
            0.03,
            0.03,
            "None",
            "Secondary",
            "About 3% + GST.",
          ],
          [
            "Razorpay",
            "Instant settlement (add-on)",
            0.005,
            0.007,
            "None",
            "Secondary",
            "0.5-0.7% extra for T+0 settlement.",
          ],
          [
            "Cashfree",
            "Domestic (standard)",
            0.0175,
            0.0195,
            "Check",
            "Secondary",
            "Often the cheapest headline rate; official page blocked, so confirm AMC/setup fees.",
          ],
          [
            "PayU",
            "Domestic",
            0.02,
            0.02,
            "Check",
            "Secondary",
            "About 2%, negotiable; strong EMI/BNPL. International about 3%.",
          ],
          [
            "Stripe (India)",
            "Cards (incl. cross-border)",
            0.043,
            0.043,
            "None",
            "Low",
            "One blog cites ~4.3% + GST; no UPI support. Treat as unverified.",
          ],
        ],
      },
      {
        id: "gateway-example",
        title: "Example: ₹3,00,000 a month through one gateway",
        compare: true,
        nameColumns: [0],
        columns: [
          { label: "Provider", kind: "text" },
          { label: "Rate used", kind: "percent" },
          { label: "Fee + GST / month", kind: "money" },
          { label: "Fee + GST / year", kind: "money" },
          { label: "Basis", kind: "long" },
        ],
        rows: [
          [
            "Razorpay (domestic)",
            0.02,
            inr(7080),
            inr(84960),
            "Assumes every rupee goes through this single rate. UPI share may lower it in practice.",
          ],
          [
            "Cashfree (mid of range)",
            0.0185,
            inr(6549),
            inr(78588),
            "Assumes every rupee goes through this single rate. UPI share may lower it in practice.",
          ],
          [
            "PayU",
            0.02,
            inr(7080),
            inr(84960),
            "Assumes every rupee goes through this single rate. UPI share may lower it in practice.",
          ],
        ],
      },
      {
        id: "couriers",
        title: "Delivery and shipping (₹ as quoted)",
        note: "Weight slabs, zone (local / metro / rest of India), COD fee and fuel surcharge change the final bill; get a rate card from the aggregator before budgeting.",
        compare: true,
        nameColumns: [0],
        columns: [
          { label: "Provider", kind: "text" },
          { label: "Type", kind: "text", facet: true },
          { label: "500 g low", kind: "money" },
          { label: "500 g high", kind: "money" },
          { label: "1 kg low", kind: "money" },
          { label: "1 kg high", kind: "money" },
          { label: "Monthly fee", kind: "money" },
          { label: "Confidence", kind: "confidence", facet: true },
          { label: "Notes", kind: "long" },
        ],
        rows: [
          [
            "Shiprocket (aggregator)",
            "Aggregator, free plan",
            inr(19),
            inr(29),
            null,
            null,
            inr(0),
            "Secondary",
            "Entry rates from ₹19-29 per 500 g depending on plan/page; 17-42 courier partners; no minimum signup.",
          ],
          [
            "Shiprocket Basic / Advanced / Pro",
            "Aggregator, paid plans",
            inr(20),
            inr(21),
            null,
            null,
            inr(1000),
            "Low",
            "Older page: ₹1,000 / 2,000 / 3,000 per month, 3-month minimum. Lower per-500 g rates on higher plans.",
          ],
          [
            "NimbusPost",
            "Aggregator",
            inr(22),
            inr(26),
            null,
            null,
            null,
            "Secondary",
            "27+ couriers, AI courier selection.",
          ],
          [
            "Delhivery (direct)",
            "Courier",
            inr(50),
            inr(90),
            inr(80),
            inr(180),
            null,
            "Secondary",
            "Surface; varies by zone. Volume discounts available.",
          ],
          [
            "Xpressbees (direct)",
            "Courier",
            inr(50),
            inr(85),
            inr(70),
            inr(110),
            null,
            "Secondary",
            "Strong COD and tracking.",
          ],
          [
            "India Post",
            "Postal",
            inr(35),
            inr(70),
            inr(50),
            inr(100),
            null,
            "Secondary",
            "Cheapest direct network; slower; good for rural.",
          ],
          [
            "Blue Dart (direct)",
            "Premium courier",
            inr(100),
            inr(150),
            inr(150),
            inr(250),
            null,
            "Secondary",
            "Fast / premium service.",
          ],
        ],
      },
    ],
    checks: [
      "Razorpay UPI: its own FAQ says 0% bank MDR but a 2% platform fee applies; several blogs claim 0% on UPI. Confirm in your dashboard. Razorpay also advertises 0% gateway fee for the first 90 days.",
      "Shiprocket plan fees (₹1,000-3,000/mo) come from an older knowledge-base page; its current free-plan rate is quoted as ₹19-29 per 500 g depending on source.",
      "Not covered (could not verify a current price): Qwen API, Mistral, Stripe India fees (one blog cites ~4.3% + GST; treat as unverified), Cashfree official page (blocked).",
    ],
    sources: [
      { label: "Razorpay pricing", url: "https://razorpay.com/pricing/" },
      {
        label: "Gateway comparison",
        url: "https://www.paritydeals.com/blog/best-payment-gateways-india-2026/",
      },
      {
        label: "Courier rates India",
        url: "https://www.shipmozo.com/blog/courier-delivery-charges-in-india-2026-comparison-rates-smart-shipping-strategy",
      },
      {
        label: "Shiprocket rates",
        url: "https://shiprocket.in/features/discounted-shipping-rates/",
      },
    ],
  },
  {
    slug: "app-dev",
    title: "App development",
    lede: "Store accounts and commissions, Macs at Indian MRP, and ways to build for iPhone without buying a Mac.",
    tables: [
      {
        id: "accounts",
        title: "Developer account fees",
        compare: true,
        nameColumns: [0],
        columns: [
          { label: "Account", kind: "text" },
          { label: "Billing", kind: "text" },
          { label: "Price", kind: "money" },
          { label: "Confidence", kind: "confidence" },
          { label: "Notes", kind: "long" },
        ],
        rows: [
          [
            "Google Play Console",
            "One-time",
            usd(25),
            "Official",
            "One-time registration fee. Personal accounts created after 13 Nov 2023 must also meet Google's testing requirements and verify an Android device before publishing.",
          ],
          [
            "Apple Developer Program",
            "Per year",
            usd(99),
            "Official",
            "Annual fee, billed in local currency. Enrolment in India is only through the Apple Developer app. Fee waiver exists for accredited educational institutions.",
          ],
          [
            "Apple Developer Program (India renewal)",
            "Per year",
            inr(8700),
            "Secondary",
            "Amount India developers add to their Apple ID to renew, per a developer-forum guide. Apple sets the INR price, so it differs from $99 at the Notes FX rate. Check at enrolment.",
          ],
          [
            "Apple Developer Enterprise Program",
            "Per year",
            usd(299),
            "Official",
            "Only for large orgs distributing internal apps. Not needed for public apps.",
          ],
        ],
      },
      {
        id: "commission",
        title: "Store commission on in-app sales",
        compare: true,
        nameColumns: [0],
        columns: [
          { label: "Store / tier", kind: "text" },
          { label: "Applies to", kind: "text" },
          { label: "Rate", kind: "percent" },
          { label: "Confidence", kind: "confidence" },
          { label: "Notes", kind: "long" },
        ],
        rows: [
          [
            "Apple standard",
            "All digital sales",
            0.3,
            "Official",
            "Default rate.",
          ],
          [
            "Apple Small Business Program",
            "Proceeds under $1M last year, or new developer",
            0.15,
            "Secondary",
            "Must apply and re-enrol every year.",
          ],
          [
            "Google Play (first $1M / yr)",
            "Per developer, per year",
            0.15,
            "Official",
            "Applied automatically. Auto-renewing subscriptions are 15% from day one.",
          ],
          [
            "Google Play (above $1M / yr)",
            "Revenue beyond $1M",
            0.3,
            "Official",
            "Some regions (US, UK, EEA, Japan, Australia) use different 20-25% rates and a 5% billing fee.",
          ],
        ],
      },
      {
        id: "macs",
        title: "Mac hardware, India MRP",
        note: "Prices from news and price trackers, not Apple's own page (it did not show prices to my fetch). Education and bank offers can cut 5-10%.",
        compare: true,
        nameColumns: [0],
        columns: [
          { label: "Mac", kind: "text" },
          { label: "Type", kind: "text", facet: true },
          { label: "Price", kind: "money" },
          { label: "Confidence", kind: "confidence" },
          { label: "Notes", kind: "long" },
        ],
        rows: [
          [
            "MacBook Neo",
            "Entry laptop",
            inr(79900),
            "Secondary",
            "Was ₹69,900 before the June hike. Cheapest new Mac; check RAM limits for Xcode.",
          ],
          [
            'MacBook Air 13" M5',
            "Laptop",
            inr(149900),
            "Secondary",
            "MRP after hike (was ₹1,19,900). Street price for 16GB/512GB was about ₹1,39,000 in Oct 2026 (Smartprix).",
          ],
          [
            'MacBook Air 15" M5',
            "Laptop",
            inr(179900),
            "Secondary",
            "MRP after hike (was ₹1,44,900).",
          ],
          [
            'MacBook Pro 14" M5',
            "Laptop",
            inr(239900),
            "Secondary",
            "Base 16GB model, MRP after hike (was ₹1,69,900).",
          ],
          [
            "Mac mini M6",
            "Desktop",
            inr(99900),
            "Secondary",
            "16GB / 256GB. Launched Aug 2026. Needs your own monitor, keyboard and mouse. Cheapest way to own a Mac for iOS builds.",
          ],
          [
            "Mac mini M5 Pro",
            "Desktop",
            inr(209900),
            "Secondary",
            "24GB / 512GB. Overkill for most app builds.",
          ],
        ],
      },
      {
        id: "no-mac",
        title: "Building for iPhone without a Mac",
        compare: true,
        nameColumns: [0],
        columns: [
          { label: "Option", kind: "text" },
          { label: "Billing", kind: "text", facet: true },
          { label: "Price", kind: "money" },
          { label: "Confidence", kind: "confidence" },
          { label: "Notes", kind: "long" },
        ],
        rows: [
          [
            "Expo EAS - Free",
            "Per month",
            usd(0),
            "Official",
            "Up to 15 iOS and 15 Android cloud builds a month, low-priority queue. Still needs the Apple $99 account.",
          ],
          [
            "Expo EAS - Starter",
            "Per month",
            usd(19),
            "Official",
            "Includes $45 build credit. iOS build = $2 (medium) or $4 (large) after credits.",
          ],
          [
            "Expo EAS - Production",
            "Per month",
            usd(199),
            "Official",
            "Includes $225 credit and more concurrency.",
          ],
          [
            "Expo EAS - one iOS build (medium)",
            "Per build",
            usd(2),
            "Official",
            "Android medium build is $1.",
          ],
          [
            "MacinCloud - managed shared Mac",
            "Per month",
            usd(25),
            "Secondary",
            "Listed range about $25-29 a month (June 2026 snapshot).",
          ],
          [
            "MacinCloud - pay as you go",
            "Per hour",
            usd(1),
            "Secondary",
            "About $1 an hour.",
          ],
          [
            "MacinCloud - dedicated M2",
            "Per month",
            usd(99),
            "Secondary",
            "$490 a year if paid annually.",
          ],
          [
            "MacinCloud - dedicated M4",
            "Per month",
            usd(124.99),
            "Secondary",
            "$1,249 a year if paid annually.",
          ],
          [
            "AWS EC2 Mac (M1 to M4 / Ultra)",
            "Per hour",
            null,
            "Not found",
            "AWS bills per second but with a 24-hour minimum per host (Apple licence rule). Hourly rate not shown on the page I could read, so left blank. Rarely cheaper than MacinCloud for one developer.",
          ],
        ],
      },
      {
        id: "first-year",
        title: "First-year launch budget (both stores)",
        compare: true,
        nameColumns: [0],
        columns: [
          { label: "Scenario", kind: "text" },
          { label: "Made of", kind: "text" },
          { label: "Total", kind: "money" },
          { label: "Notes", kind: "long" },
        ],
        rows: [
          [
            "Android only",
            "Play fee",
            usd(25),
            "Cheapest start. No Mac needed.",
          ],
          [
            "Both stores + Expo EAS Starter 3 months",
            "Play + Apple + 3 x EAS Starter",
            usd(181),
            "No Mac purchase. Cloud builds only.",
          ],
          [
            "Both stores + MacinCloud managed 3 months",
            "Play + Apple + 3 x managed",
            usd(199),
            "Rented remote Mac for builds and TestFlight uploads.",
          ],
          [
            "Both stores + buy Mac mini M6",
            "Play + Apple + Mac mini",
            usd(1159.984652),
            "Own machine. Monitor and keyboard not included.",
          ],
          [
            'Both stores + buy MacBook Air 13" M5',
            "Play + Apple + MacBook Air",
            usd(1678.495489),
            "Portable. Uses MRP, not street price.",
          ],
        ],
      },
    ],
    checks: [],
    sources: [
      {
        label: "Google Play fees",
        url: "https://support.google.com/googleplay/android-developer/answer/112622",
      },
      {
        label: "Play Console registration",
        url: "https://support.google.com/googleplay/android-developer/answer/6112435",
      },
      {
        label: "Apple Developer enrolment",
        url: "https://developer.apple.com/support/enrollment/",
      },
      {
        label: "Apple India renewal (INR)",
        url: "https://developer.apple.com/forums/thread/746357",
      },
      {
        label: "Small business programs",
        url: "https://appbot.co/blog/app-developers-apple-google-small-business-programs/",
      },
      {
        label: "Apple India price hike (27 Jun 2026)",
        url: "https://www.goodreturns.in/news/apple-price-hike-india-2026-macbook-pro-up-rs-70-000-ipad-air-up-42-mac-mini-homepod-iphone-1518509.html",
      },
      {
        label: "MacBook Air 13 M5 street price",
        url: "https://www.smartprix.com/laptops/apple-macbook-air-13-2026-laptop-apple-m5-ppd1z9tazegp",
      },
      {
        label: "Mac mini M6 / M5 Pro India",
        url: "https://telecomtalk.info/mac-mini-launched-with-m6-m5-pro/1011204/",
      },
      { label: "Expo EAS pricing", url: "https://expo.dev/pricing" },
      {
        label: "MacinCloud pricing (third-party)",
        url: "https://www.greenmini.nl/compare/macincloud-alternative/",
      },
      {
        label: "AWS EC2 Mac",
        url: "https://aws.amazon.com/ec2/instance-types/mac/",
      },
    ],
  },
];

/** The workbook's sheets, before any edits the team has saved. */
export const SHEETS: Sheet[] = WORKBOOK.map((sheet) => ({
  ...sheet,
  tables: sheet.tables.map((table) => ({
    ...table,
    rows: table.rows.map((cells, i) => ({ id: `w${i}`, cells })),
  })),
}));

export function sheetBySlug(slug: string | undefined) {
  return SHEETS.find((s) => s.slug === slug);
}
