import "server-only";
import { readFile } from "node:fs/promises";
import path from "node:path";
import { cache } from "react";
import type { Compare } from "@/lib/judge";

/**
 * The Python problems, their test cases, and their reference solutions.
 *
 * Server-side only, and that is the point. While this shipped to the browser
 * every student could open the network tab and read the expected output of
 * every case — which is the one thing a judge exists to withhold. Now the
 * page sends code up and gets a verdict back, and the answers never leave.
 *
 * Generated by scripts/build-python-tests.py, which computes the expectations
 * by running reference solutions rather than trusting anyone to type them.
 */

export type JudgedProblem = {
  slug: string;
  entry_point: string;
  starter_code: string;
  solution_py: string;
  note: string;
  tests: { compare: Compare; cases: { args: unknown[]; expect: unknown }[] };
};

/**
 * What a student is allowed to see about a problem before they solve it: the
 * starter code, the shape of a few cases, and — once they ask — the reference
 * solution. Never the full set of expectations.
 */
export type ProblemBrief = {
  slug: string;
  starter_code: string;
  note: string;
  case_count: number;
  samples: { args: unknown[]; expect: unknown }[];
};

const FILE = path.join(process.cwd(), "content", "python-tests.json");

/** Read once per process; it is a static file and never changes at runtime. */
let loaded: Promise<Map<string, JudgedProblem>> | null = null;

export function allProblems(): Promise<Map<string, JudgedProblem>> {
  loaded ??= readFile(FILE, "utf8").then((raw) => {
    const list = JSON.parse(raw) as JudgedProblem[];
    return new Map(list.map((problem) => [problem.slug, problem]));
  });
  return loaded;
}

export const getProblem = cache(async (slug: string) => {
  return (await allProblems()).get(slug) ?? null;
});

/**
 * The public half of every problem, keyed by slug.
 *
 * Three sample cases, matching what LeetCode itself shows — enough to
 * understand the shape of the answer, not enough to hard-code one. The
 * remaining cases exist only on the server.
 */
export async function briefs(): Promise<Record<string, ProblemBrief>> {
  const problems = await allProblems();
  const out: Record<string, ProblemBrief> = {};

  for (const [slug, problem] of problems) {
    out[slug] = {
      slug,
      starter_code: problem.starter_code,
      note: problem.note,
      case_count: problem.tests.cases.length,
      samples: problem.tests.cases.slice(0, 3),
    };
  }

  return out;
}
