import "server-only";
import { readFile } from "node:fs/promises";
import path from "node:path";

/**
 * The answer to each SQL practice question, keyed by its position.
 *
 * Generated by scripts/build_sql_practice.py, which computes every one of
 * them by running the reference solution against the same database the
 * browser builds. Nobody types an expected result by hand: a hand-written one
 * is a second implementation of the question that can disagree with the
 * first.
 *
 * Server-side only, and read once per process — it is a static file.
 */

export type Grid = { columns: string[]; rows: unknown[][] };

/**
 * `check_sql` is set for the one question that changes data rather than
 * returning it. An UPDATE has no rows to compare, so the answer is the state
 * of the table afterwards, and this is the query that reads it back.
 */
export type SqlAnswer = { expected_result: Grid; check_sql: string | null };

const FILE = path.join(process.cwd(), "content", "sql-answers.json");

let loaded: Promise<Record<string, SqlAnswer>> | null = null;

export function allAnswers(): Promise<Record<string, SqlAnswer>> {
  loaded ??= readFile(FILE, "utf8").then(
    (raw) => JSON.parse(raw) as Record<string, SqlAnswer>,
  );
  return loaded;
}

export async function sqlAnswer(position: string): Promise<SqlAnswer | null> {
  return (await allAnswers())[position] ?? null;
}
