import "server-only";
import {
  siAnsible,
  siApacheairflow,
  siApachecassandra,
  siApacheflink,
  siApachehadoop,
  siApachehive,
  siApachejmeter,
  siApachekafka,
  siApacheparquet,
  siApachesolr,
  siApachespark,
  siApachestorm,
  siArgo,
  siCloudflare,
  siConsul,
  siCypress,
  siDask,
  siDatadog,
  siDjango,
  siDocker,
  siDotnet,
  siElasticsearch,
  siExpress,
  siFastapi,
  siFlask,
  siFormik,
  siGin,
  siGithubactions,
  siGitlab,
  siGo,
  siGooglecloud,
  siGooglecolab,
  siGrafana,
  siHelm,
  siIstio,
  siJenkins,
  siJest,
  siJupyter,
  siKong,
  siKubernetes,
  siLocust,
  siMlflow,
  siMongodb,
  siNestjs,
  siNextdotjs,
  siNginx,
  siNodedotjs,
  siNumpy,
  siNuxt,
  siOpenjdk,
  siOwasp,
  siPandas,
  siPostgresql,
  siPresto,
  siPrefect,
  siPython,
  siPrometheus,
  siPulumi,
  siPytest,
  siPytorch,
  siRabbitmq,
  siReact,
  siReacthookform,
  siRecoil,
  siRedis,
  siRedux,
  siScikitlearn,
  siSelenium,
  siSnyk,
  siSpringboot,
  siSqlalchemy,
  siStreamlit,
  siStyledcomponents,
  siSvelte,
  siTailwindcss,
  siTensorflow,
  siTerraform,
  siTrino,
  siTypeorm,
  siVuedotjs,
} from "simple-icons";

type Icon = { path: string; hex: string; title: string };

/**
 * Every technology named in the notes that Simple Icons actually has a mark
 * for, keyed on the exact text used in the markdown.
 *
 * Not every name here gets one — AWS, Azure, Amazon S3/SQS/DynamoDB,
 * HAProxy, Varnish, Kubeflow, Luigi, Fiber, Zustand and Playwright were
 * removed from Simple Icons (mostly over trademark disputes) and are not
 * present at any version. `techIcon` returns null for those, and the note
 * falls back to plain text — a missing logo, not a broken one.
 */
const REGISTRY: Record<string, Icon> = {
  NGINX: siNginx,
  Redis: siRedis,
  Cloudflare: siCloudflare,
  PostgreSQL: siPostgresql,
  MongoDB: siMongodb,
  Cassandra: siApachecassandra,
  Kafka: siApachekafka,
  RabbitMQ: siRabbitmq,
  Elasticsearch: siElasticsearch,
  Solr: siApachesolr,
  Kong: siKong,
  Spark: siApachespark,
  Hadoop: siApachehadoop,
  HDFS: siApachehadoop,
  Flink: siApacheflink,
  Storm: siApachestorm,
  Airflow: siApacheairflow,
  Prefect: siPrefect,
  Parquet: siApacheparquet,
  Python: siPython,
  Presto: siPresto,
  Hive: siApachehive,
  Trino: siTrino,
  Pandas: siPandas,
  NumPy: siNumpy,
  Dask: siDask,
  "scikit-learn": siScikitlearn,
  TensorFlow: siTensorflow,
  PyTorch: siPytorch,
  MLflow: siMlflow,
  FastAPI: siFastapi,
  Jupyter: siJupyter,
  "Google Colab": siGooglecolab,
  Django: siDjango,
  Flask: siFlask,
  Streamlit: siStreamlit,
  "Node.js": siNodedotjs,
  Express: siExpress,
  NestJS: siNestjs,
  Java: siOpenjdk,
  "Spring Boot": siSpringboot,
  Go: siGo,
  Gin: siGin,
  ".NET": siDotnet,
  SQLAlchemy: siSqlalchemy,
  TypeORM: siTypeorm,
  React: siReact,
  Vue: siVuedotjs,
  Svelte: siSvelte,
  "Next.js": siNextdotjs,
  "Nuxt.js": siNuxt,
  "Tailwind CSS": siTailwindcss,
  "Styled Components": siStyledcomponents,
  Redux: siRedux,
  Recoil: siRecoil,
  Formik: siFormik,
  "React Hook Form": siReacthookform,
  "GitHub Actions": siGithubactions,
  "GitLab CI": siGitlab,
  Jenkins: siJenkins,
  ArgoCD: siArgo,
  Docker: siDocker,
  Kubernetes: siKubernetes,
  "Docker Swarm": siDocker,
  Prometheus: siPrometheus,
  Grafana: siGrafana,
  Datadog: siDatadog,
  Terraform: siTerraform,
  Pulumi: siPulumi,
  Ansible: siAnsible,
  Helm: siHelm,
  Istio: siIstio,
  Consul: siConsul,
  GCP: siGooglecloud,
  Pytest: siPytest,
  Jest: siJest,
  Selenium: siSelenium,
  Cypress: siCypress,
  "OWASP ZAP": siOwasp,
  Snyk: siSnyk,
  Locust: siLocust,
  JMeter: siApachejmeter,
};

export function techIcon(name: string): Icon | null {
  return REGISTRY[name] ?? null;
}
