"use client";

import { useCallback, useEffect, useRef, useState } from "react";
import {
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ExternalLink,
  Eye,
  Lightbulb,
  Loader2,
  PanelLeftClose,
  PanelLeftOpen,
  PanelRightClose,
  PanelRightOpen,
  Play,
  RotateCcw,
  X,
} from "lucide-react";
import { ProofUpload } from "@/components/dashboard/ProofUpload";
import { createClient } from "@/lib/supabase/client";
import {
  displayArgs,
  display,
  isCorrect,
  type JudgedProblem,
} from "@/lib/judge";
import { cn } from "@/lib/utils";

export type PyQuestion = {
  id: string;
  topic: string;
  difficulty: "easy" | "medium" | "hard";
  position: number;
  title: string;
  prompt_md: string | null;
  hint_md: string | null;
  leetcode_url: string | null;
  has_judge: boolean;
};

const DIFF_TONE: Record<string, string> = {
  easy: "bg-leaf-wash text-leaf-deep",
  medium: "bg-amber-wash text-amber-deep",
  hard: "bg-brand-wash text-brand-deep",
};

/** Long enough for an O(n²) answer on our inputs, short enough to notice. */
const TIME_LIMIT_MS = 10_000;

/** The first run also pays for the runtime download on a cold cache. */
const COLD_LIMIT_MS = 120_000;

const slugOf = (url: string | null) =>
  url ? (/\/problems\/([^/]+)/.exec(url)?.[1] ?? null) : null;

type CaseResult = {
  index: number;
  ok: boolean;
  got?: unknown;
  error?: string;
};

type Run =
  | { at: "idle" }
  | { at: "booting" }
  | { at: "running" }
  | { at: "timeout" }
  | { at: "fatal"; message: string }
  | { at: "done"; results: CaseResult[]; passed: number; total: number };

/**
 * Starts the judge worker.
 *
 * Through a blob rather than a path, so the bundler never sees a worker to
 * compile. Turbopack rewrites the ones it finds to load their chunks with
 * importScripts, which a module worker forbids — the worker then dies with
 * "classic web workers are not supported" before it runs a line. A one-line
 * bootstrap that pulls in a plain script from public/ sidesteps all of it.
 */
function startWorker() {
  const base = new URL("/pyodide/", window.location.href).href;
  const script = new URL("/python-worker.js", window.location.href).href;

  // Absolute URLs, because a blob worker cannot resolve a path against the
  // page's origin — everything it loads has to be spelled out.
  const bootstrap =
    `self.__PYODIDE_BASE__ = ${JSON.stringify(base)};\n` +
    `importScripts(${JSON.stringify(script)});`;

  const blob = new Blob([bootstrap], { type: "text/javascript" });
  return new Worker(URL.createObjectURL(blob));
}

/** Pointer-drag sizing, matching the SQL workspace's splitters. */
function useDragSize(initial: number, min: number, max: number) {
  const [size, setSize] = useState(initial);
  const state = useRef({ start: 0, base: 0, sign: 1, axis: "x" as "x" | "y" });

  const begin = useCallback(
    (event: React.PointerEvent, sign: 1 | -1, axis: "x" | "y" = "x") => {
      event.preventDefault();
      state.current = {
        start: axis === "x" ? event.clientX : event.clientY,
        base: size,
        sign,
        axis,
      };
      const move = (moveEvent: PointerEvent) => {
        const { start, base, sign: s, axis: a } = state.current;
        const now = a === "x" ? moveEvent.clientX : moveEvent.clientY;
        setSize(Math.min(max, Math.max(min, base + (now - start) * s)));
      };
      const up = () => {
        window.removeEventListener("pointermove", move);
        window.removeEventListener("pointerup", up);
        document.body.style.userSelect = "";
      };
      document.body.style.userSelect = "none";
      window.addEventListener("pointermove", move);
      window.addEventListener("pointerup", up);
    },
    [size, min, max],
  );

  return [size, begin] as const;
}

/**
 * The Python workspace: a real judge, in the browser.
 *
 * LeetCode publishes no API and its hidden tests are not ours to take, so the
 * cases here are our own — generated by running a reference solution against
 * inputs we chose, the same way the SQL practice computes its expected grids.
 * The student's code runs in a worker through Pyodide, which is CPython
 * compiled to WebAssembly: no server, no queue, no bill, and a verdict in a
 * few milliseconds once the runtime has loaded.
 */
export function PythonJudge({
  questions,
  solved: initialSolved,
}: {
  questions: PyQuestion[];
  solved: string[];
}) {
  const [index, setIndex] = useState(0);
  /*
   * The editor holds the student's edit, or null while they have not touched
   * it — the starter code is then derived from whichever problem is open.
   * Seeding state from an effect would have to fire twice (once when the
   * problem changes, once when the fetched tests arrive) and race with typing.
   */
  const [edited, setEdited] = useState<string | null>(null);
  const [run, setRun] = useState<Run>({ at: "idle" });
  const [solved, setSolved] = useState<string[]>(initialSolved);
  const [showHint, setShowHint] = useState(false);
  const [showSolution, setShowSolution] = useState(false);

  const [leftOpen, setLeftOpen] = useState(true);
  const [rightOpen, setRightOpen] = useState(true);
  const [leftWidth, dragLeft] = useDragSize(272, 200, 420);
  const [rightWidth, dragRight] = useDragSize(360, 280, 620);
  const [editorHeight, dragEditor] = useDragSize(300, 140, 700);

  const [problems, setProblems] = useState<Record<string, JudgedProblem>>({});
  const [pyReady, setPyReady] = useState(false);
  const workerRef = useRef<Worker | null>(null);
  const nextId = useRef(0);

  const question = questions[index];
  const slug = slugOf(question?.leetcode_url ?? null);
  const problem = slug ? problems[slug] : undefined;
  const code = edited ?? problem?.starter_code ?? "";

  /*
   * The test file is fetched once, lazily. It is 42 KB (9 KB over the wire)
   * and only a student who opens the Python track ever needs it, so it has no
   * business in the page bundle.
   */
  useEffect(() => {
    let cancelled = false;
    fetch("/python-tests.json")
      .then((response) => (response.ok ? response.json() : []))
      .then((list: JudgedProblem[]) => {
        if (cancelled) return;
        setProblems(Object.fromEntries(list.map((p) => [p.slug, p])));
      })
      .catch(() => {});
    return () => {
      cancelled = true;
    };
  }, []);

  /*
   * Start the runtime downloading immediately. It is the slowest thing here by
   * a wide margin and it is entirely independent of which problem is open, so
   * there is no reason to make the first Run wait for it.
   */
  useEffect(() => {
    const worker = startWorker();
    workerRef.current = worker;
    worker.addEventListener("message", (event: MessageEvent) => {
      if (event.data?.ready) setPyReady(true);
    });
    worker.postMessage({ warmup: true });
    return () => {
      worker.terminate();
      workerRef.current = null;
    };
  }, []);

  function go(next: number) {
    setIndex(next);
    setRun({ at: "idle" });
    setShowHint(false);
    setShowSolution(false);
    setEdited(null);
  }

  async function markSolved(id: string) {
    if (solved.includes(id)) return;
    setSolved((prev) => [...prev, id]);
    const supabase = createClient();
    const { data } = await supabase.auth.getUser();
    if (!data.user) return;
    await supabase
      .from("practice_progress")
      .upsert({ question_id: id, user_id: data.user.id });
  }

  function judge() {
    if (!problem || !question) return;
    if (run.at === "running" || run.at === "booting") return;

    setRun({ at: pyReady ? "running" : "booting" });

    if (!workerRef.current) workerRef.current = startWorker();
    const worker = workerRef.current;
    nextId.current += 1;
    const id = nextId.current;

    /*
     * The timeout is the only defence against an infinite loop, and it works
     * by killing the thread. A terminated worker cannot reply, so the timer
     * owns the outcome from here.
     */
    const timer = setTimeout(
      () => {
        worker.terminate();
        workerRef.current = null;
        setPyReady(false);
        setRun({ at: "timeout" });
      },
      pyReady ? TIME_LIMIT_MS : COLD_LIMIT_MS,
    );

    worker.onmessage = (event) => {
      if (event.data.ready) {
        setPyReady(true);
        return;
      }
      if (event.data.id !== id) return;
      clearTimeout(timer);

      if (!event.data.ok) {
        setRun({ at: "fatal", message: event.data.error });
        return;
      }
      const payload = event.data.payload as {
        fatal?: string;
        results?: { got?: unknown; error?: string }[];
      };
      if (payload.fatal) {
        setRun({ at: "fatal", message: payload.fatal });
        return;
      }

      const cases = problem.tests.cases;
      const results: CaseResult[] = (payload.results ?? []).map((row, i) => ({
        index: i,
        ok:
          row.error === undefined &&
          isCorrect(row.got, cases[i].expect, problem.tests.compare),
        got: row.got,
        error: row.error,
      }));
      const passed = results.filter((r) => r.ok).length;

      setRun({ at: "done", results, passed, total: cases.length });
      if (passed === cases.length && cases.length > 0) {
        void markSolved(question.id);
      }
    };

    worker.postMessage({
      id,
      source: code,
      entry: problem.entry_point,
      cases: problem.tests.cases.map((c) => ({ args: c.args })),
      compare: problem.tests.compare,
    });
  }

  if (!question) {
    return (
      <div className="card m-6 p-8 text-center">
        <p className="text-ink-soft text-[0.9375rem]">
          No questions published.
        </p>
      </div>
    );
  }

  const isSolved = solved.includes(question.id);
  const done = questions.filter((q) => solved.includes(q.id)).length;
  const pct = questions.length ? (done / questions.length) * 100 : 0;
  const firstFail =
    run.at === "done" ? run.results.find((r) => !r.ok) : undefined;

  return (
    <div className="flex h-full flex-col">
      {/* Toolbar ------------------------------------------------------- */}
      <div className="border-line bg-surface flex shrink-0 flex-wrap items-center gap-x-3 gap-y-2 border-b px-3 py-2">
        <button
          type="button"
          onClick={() => setLeftOpen((v) => !v)}
          aria-label={leftOpen ? "Hide problems" : "Show problems"}
          className="text-ink-soft hover:bg-mist hover:text-ink hidden rounded-lg p-1.5 transition-colors lg:grid"
        >
          {leftOpen ? (
            <PanelLeftClose className="size-4" strokeWidth={2} aria-hidden />
          ) : (
            <PanelLeftOpen className="size-4" strokeWidth={2} aria-hidden />
          )}
        </button>

        <div className="flex items-center gap-1">
          <button
            type="button"
            onClick={() => go(Math.max(0, index - 1))}
            disabled={index === 0}
            className="border-line text-ink-soft hover:text-ink grid size-7 place-items-center rounded-md border transition-colors disabled:opacity-30"
            aria-label="Previous problem"
          >
            <ChevronLeft className="size-3.5" strokeWidth={2} aria-hidden />
          </button>
          <span className="text-ink-faint px-1 font-mono text-[0.75rem] tabular-nums">
            {index + 1}/{questions.length}
          </span>
          <button
            type="button"
            onClick={() => go(Math.min(questions.length - 1, index + 1))}
            disabled={index === questions.length - 1}
            className="border-line text-ink-soft hover:text-ink grid size-7 place-items-center rounded-md border transition-colors disabled:opacity-30"
            aria-label="Next problem"
          >
            <ChevronRight className="size-3.5" strokeWidth={2} aria-hidden />
          </button>
        </div>

        <span className="text-ink min-w-0 flex-1 truncate text-[0.875rem] font-semibold">
          {question.title}
        </span>

        <div className="flex items-center gap-2.5">
          <span className="bg-mist hidden h-1.5 w-28 overflow-hidden rounded-full sm:block">
            <span
              className="bg-leaf-deep block h-full rounded-full transition-[width] duration-500"
              style={{ width: `${pct}%` }}
            />
          </span>
          <span className="text-ink-soft font-mono text-[0.75rem] tabular-nums">
            {done}/{questions.length} solved
          </span>
        </div>

        <span
          className={cn(
            "rounded-full px-2.5 py-0.5 text-[0.6875rem] font-semibold capitalize",
            DIFF_TONE[question.difficulty],
          )}
        >
          {question.difficulty}
        </span>

        <button
          type="button"
          onClick={() => setEdited(null)}
          className="border-line text-ink-soft hover:text-ink inline-flex items-center gap-1.5 rounded-lg border px-2.5 py-1.5 text-[0.8125rem] font-medium transition-colors"
        >
          <RotateCcw className="size-3.5" strokeWidth={2} aria-hidden />
          <span className="hidden sm:inline">Reset code</span>
        </button>

        <button
          type="button"
          onClick={judge}
          disabled={!problem || run.at === "running" || run.at === "booting"}
          className="bg-ink text-cta-fg hover:bg-brand-deep disabled:hover:bg-ink inline-flex items-center gap-1.5 rounded-lg px-3.5 py-1.5 text-[0.8125rem] font-semibold transition-colors disabled:opacity-40"
        >
          {run.at === "running" || run.at === "booting" ? (
            <Loader2 className="size-3.5 animate-spin" aria-hidden />
          ) : (
            <Play className="size-3.5" strokeWidth={2.5} aria-hidden />
          )}
          {run.at === "booting"
            ? "Starting Python…"
            : run.at === "running"
              ? "Running…"
              : "Run tests"}
        </button>

        <button
          type="button"
          onClick={() => setRightOpen((v) => !v)}
          aria-label={rightOpen ? "Hide problem" : "Show problem"}
          className="text-ink-soft hover:bg-mist hover:text-ink hidden rounded-lg p-1.5 transition-colors lg:grid"
        >
          {rightOpen ? (
            <PanelRightClose className="size-4" strokeWidth={2} aria-hidden />
          ) : (
            <PanelRightOpen className="size-4" strokeWidth={2} aria-hidden />
          )}
        </button>
      </div>

      <div className="flex min-h-0 flex-1 flex-col lg:flex-row">
        {/* Left: the problem list, grouped as the sheet groups it */}
        {leftOpen && (
          <>
            <aside
              style={{ width: leftWidth }}
              className="border-line bg-mist hidden shrink-0 overflow-y-auto border-r lg:block"
            >
              <ProblemList
                questions={questions}
                index={index}
                solved={solved}
                onPick={go}
              />
            </aside>
            <Splitter onPointerDown={(e) => dragLeft(e, 1)} />
          </>
        )}

        {/* Centre: editor over results */}
        <div className="flex min-h-0 min-w-0 flex-1 flex-col">
          <div
            style={{ height: editorHeight }}
            className="bg-night flex shrink-0 flex-col"
          >
            <label className="sr-only" htmlFor="py-editor">
              Your Python solution
            </label>
            <textarea
              id="py-editor"
              value={code}
              onChange={(event) => setEdited(event.target.value)}
              onKeyDown={(event) => {
                if ((event.metaKey || event.ctrlKey) && event.key === "Enter") {
                  event.preventDefault();
                  judge();
                }
                // A code editor that outdents on Tab is not a code editor.
                if (event.key === "Tab") {
                  event.preventDefault();
                  const target = event.currentTarget;
                  const { selectionStart: from, selectionEnd: to } = target;
                  setEdited(`${code.slice(0, from)}    ${code.slice(to)}`);
                  requestAnimationFrame(() => {
                    target.selectionStart = target.selectionEnd = from + 4;
                  });
                }
              }}
              spellCheck={false}
              placeholder={problem ? "" : "Loading the problem's starter code…"}
              className="h-full w-full resize-none border-0 bg-transparent p-4 font-mono text-[0.875rem] leading-[1.7] text-white/90 placeholder:text-white/25 focus:outline-none"
            />
          </div>

          <Splitter horizontal onPointerDown={(e) => dragEditor(e, 1, "y")} />

          <div className="bg-surface flex min-h-0 flex-1 flex-col">
            <Verdict run={run} />
            <Results
              run={run}
              problem={problem}
              firstFail={firstFail}
              solved={isSolved}
            />
          </div>
        </div>

        {/* Right: the problem statement */}
        {rightOpen && (
          <>
            <Splitter onPointerDown={(e) => dragRight(e, -1)} />
            <aside
              style={{ width: rightWidth }}
              className="border-line bg-mist hidden shrink-0 overflow-y-auto border-l lg:block"
            >
              <Statement
                question={question}
                problem={problem}
                solved={isSolved}
                showHint={showHint}
                showSolution={showSolution}
                onHint={() => setShowHint((v) => !v)}
                onSolution={() => setShowSolution((v) => !v)}
                onSolved={() => void markSolved(question.id)}
              />
            </aside>
          </>
        )}
      </div>

      <div className="border-line max-h-[55vh] shrink-0 overflow-y-auto border-t lg:hidden">
        <Statement
          question={question}
          problem={problem}
          solved={isSolved}
          showHint={showHint}
          showSolution={showSolution}
          onHint={() => setShowHint((v) => !v)}
          onSolution={() => setShowSolution((v) => !v)}
          onSolved={() => void markSolved(question.id)}
        />
        <ProblemList
          questions={questions}
          index={index}
          solved={solved}
          onPick={go}
        />
      </div>
    </div>
  );
}

function Splitter({
  horizontal,
  onPointerDown,
}: {
  horizontal?: boolean;
  onPointerDown: (event: React.PointerEvent) => void;
}) {
  return (
    <div
      onPointerDown={onPointerDown}
      role="separator"
      aria-orientation={horizontal ? "horizontal" : "vertical"}
      aria-label="Resize"
      className={cn(
        "bg-line hover:bg-brand active:bg-brand shrink-0 transition-colors",
        horizontal
          ? "h-1 w-full cursor-row-resize"
          : "hidden w-1 cursor-col-resize lg:block",
      )}
    />
  );
}

function Verdict({ run }: { run: Run }) {
  if (run.at === "idle" || run.at === "running" || run.at === "booting")
    return null;

  if (run.at === "timeout") {
    return (
      <p className="bg-amber-wash text-amber-deep shrink-0 px-4 py-2.5 text-[0.875rem] font-semibold">
        Timed out after 10 seconds — most likely a loop that never ends.
      </p>
    );
  }

  if (run.at === "fatal") {
    return (
      <pre className="bg-amber-wash text-amber-deep max-h-32 shrink-0 overflow-auto px-4 py-2.5 font-mono text-[0.8125rem] whitespace-pre-wrap">
        {run.message}
      </pre>
    );
  }

  const all = run.passed === run.total;
  return (
    <p
      className={cn(
        "flex shrink-0 items-center gap-2 px-4 py-2.5 text-[0.875rem] font-semibold",
        all ? "bg-leaf-wash text-leaf-deep" : "bg-amber-wash text-amber-deep",
      )}
    >
      {all ? (
        <>
          <Check className="size-4" strokeWidth={3} aria-hidden />
          Accepted — {run.passed}/{run.total} test cases passed, and this is
          ticked off.
        </>
      ) : (
        <>
          <X className="size-4" strokeWidth={3} aria-hidden />
          Wrong answer — {run.passed}/{run.total} test cases passed.
        </>
      )}
    </p>
  );
}

function Results({
  run,
  problem,
  firstFail,
  solved,
}: {
  run: Run;
  problem: JudgedProblem | undefined;
  firstFail: CaseResult | undefined;
  solved: boolean;
}) {
  if (run.at === "booting") {
    return (
      <p className="text-ink-faint px-4 py-4 text-[0.875rem]">
        Starting Python in your browser. This happens once and is then cached —
        about 6 MB, and nothing is sent to a server.
      </p>
    );
  }

  if (run.at !== "done" || !problem) {
    return (
      <p className="text-ink-faint px-4 py-4 text-[0.875rem]">
        {solved
          ? "Solved. Run again any time."
          : "Write your solution and press Run tests. Ctrl/⌘ + Enter also works."}
      </p>
    );
  }

  const cases = problem.tests.cases;

  return (
    <div className="min-h-0 flex-1 overflow-auto p-4">
      {/* The failing case first — it is the only one anyone reads. */}
      {firstFail && (
        <div className="border-line bg-mist mb-4 overflow-hidden rounded-xl border">
          <p className="eyebrow border-line-soft border-b px-4 py-2">
            Failing test case
          </p>
          <dl className="grid gap-3 p-4 text-[0.8125rem] sm:grid-cols-[6rem_1fr]">
            <dt className="text-ink-faint font-semibold">Input</dt>
            <dd className="text-ink-soft font-mono break-all">
              {displayArgs(cases[firstFail.index].args)}
            </dd>

            <dt className="text-ink-faint font-semibold">Expected</dt>
            <dd className="text-leaf-deep font-mono break-all">
              {display(cases[firstFail.index].expect)}
            </dd>

            <dt className="text-ink-faint font-semibold">
              {firstFail.error ? "Error" : "You returned"}
            </dt>
            <dd className="text-amber-deep font-mono break-all">
              {firstFail.error ?? display(firstFail.got)}
            </dd>
          </dl>
        </div>
      )}

      <ol className="flex flex-wrap gap-1.5">
        {run.results.map((result) => (
          <li key={result.index}>
            <span
              title={`Case ${result.index + 1}: ${displayArgs(cases[result.index].args)}`}
              className={cn(
                "grid size-7 place-items-center rounded-md font-mono text-[0.6875rem] font-semibold",
                result.ok
                  ? "bg-leaf-wash text-leaf-deep"
                  : "bg-amber-wash text-amber-deep",
              )}
            >
              {result.index + 1}
            </span>
          </li>
        ))}
      </ol>
    </div>
  );
}

function ProblemList({
  questions,
  index,
  solved,
  onPick,
}: {
  questions: PyQuestion[];
  index: number;
  solved: string[];
  onPick: (next: number) => void;
}) {
  const topics = new Map<string, { q: PyQuestion; i: number }[]>();
  questions.forEach((q, i) => {
    if (!topics.has(q.topic)) topics.set(q.topic, []);
    topics.get(q.topic)!.push({ q, i });
  });

  return (
    <div className="pb-6">
      {[...topics.entries()].map(([topic, entries]) => {
        const open = entries.some(({ i }) => i === index);
        const doneHere = entries.filter(({ q }) =>
          solved.includes(q.id),
        ).length;
        return (
          <details
            key={topic}
            open={open}
            className="border-line-soft border-b"
          >
            <summary className="text-ink hover:bg-surface flex cursor-pointer list-none items-center gap-2 px-4 py-3 text-[0.8125rem] font-semibold [&::-webkit-details-marker]:hidden">
              <ChevronDown
                className="size-3.5 shrink-0"
                strokeWidth={2.5}
                aria-hidden
              />
              {topic}
              <span className="text-ink-faint ml-auto font-mono text-[0.75rem]">
                {doneHere}/{entries.length}
              </span>
            </summary>
            <ul className="pb-2">
              {entries.map(({ q, i }) => (
                <li key={q.id}>
                  <button
                    type="button"
                    onClick={() => onPick(i)}
                    aria-current={i === index ? "true" : undefined}
                    className={cn(
                      "flex w-full items-start gap-2 border-l-2 py-1.5 pr-3 pl-3 text-left text-[0.8125rem] leading-snug transition-colors",
                      i === index
                        ? "border-brand bg-surface text-ink font-medium"
                        : "text-ink-soft hover:bg-surface hover:text-ink border-transparent",
                    )}
                  >
                    <span
                      className={cn(
                        "mt-px grid size-4 shrink-0 place-items-center rounded-full text-[0.5625rem]",
                        solved.includes(q.id)
                          ? "bg-leaf-deep text-white"
                          : "text-ink-faint border-line border font-mono",
                      )}
                    >
                      {solved.includes(q.id) ? (
                        <Check
                          className="size-2.5"
                          strokeWidth={4}
                          aria-hidden
                        />
                      ) : (
                        i + 1
                      )}
                    </span>
                    <span className="min-w-0">
                      {q.title}
                      {!q.has_judge && (
                        <span className="text-ink-faint ml-1.5 text-[0.6875rem]">
                          (review)
                        </span>
                      )}
                    </span>
                  </button>
                </li>
              ))}
            </ul>
          </details>
        );
      })}
    </div>
  );
}

function Statement({
  question,
  problem,
  solved,
  showHint,
  showSolution,
  onHint,
  onSolution,
  onSolved,
}: {
  question: PyQuestion;
  problem: JudgedProblem | undefined;
  solved: boolean;
  showHint: boolean;
  showSolution: boolean;
  onHint: () => void;
  onSolution: () => void;
  onSolved: () => void;
}) {
  return (
    <div className="p-4">
      <div className="flex items-center gap-2">
        <p className="eyebrow">{question.topic}</p>
        {solved && (
          <span className="bg-leaf-wash text-leaf-deep ml-auto inline-flex items-center gap-1 rounded-full px-2 py-0.5 text-[0.6875rem] font-semibold">
            <Check className="size-3" strokeWidth={3} aria-hidden />
            Solved
          </span>
        )}
      </div>

      <h2 className="text-ink mt-2 text-[1rem] leading-snug font-semibold">
        {question.title}
      </h2>
      {question.prompt_md && (
        <p className="text-ink-soft mt-2 text-[0.875rem] leading-relaxed">
          {question.prompt_md}
        </p>
      )}

      {question.leetcode_url && (
        <a
          href={question.leetcode_url}
          target="_blank"
          rel="noreferrer noopener"
          className="text-brand-deep mt-3 inline-flex items-center gap-1.5 text-[0.8125rem] font-semibold hover:underline"
        >
          Read the full statement on LeetCode
          <ExternalLink className="size-3" strokeWidth={2} aria-hidden />
        </a>
      )}

      {!question.has_judge && (
        <div className="border-amber/30 bg-amber-wash mt-4 rounded-lg border px-3 py-2.5">
          <p className="text-ink-soft text-[0.8125rem] leading-relaxed">
            A design problem — a sequence of operations rather than one function
            — so it is not run here. Solve it on LeetCode and upload the
            accepted submission; it is read and checked before it counts.
          </p>
          <div className="mt-2.5">
            <ProofUpload
              questionId={question.id}
              solved={solved}
              onSolved={onSolved}
            />
          </div>
        </div>
      )}

      {problem?.note && (
        <p className="text-ink-faint mt-3 text-[0.8125rem] leading-relaxed">
          {problem.note}
        </p>
      )}

      <div className="mt-4 grid grid-cols-2 gap-2">
        <button
          type="button"
          onClick={onHint}
          disabled={!question.hint_md}
          className="border-line bg-surface text-amber-deep hover:border-amber inline-flex items-center justify-center gap-1.5 rounded-lg border px-3 py-2 text-[0.8125rem] font-semibold transition-colors disabled:opacity-40"
        >
          <Lightbulb className="size-3.5" strokeWidth={2} aria-hidden />
          {showHint ? "Hide hint" : "Get hint"}
        </button>
        <button
          type="button"
          onClick={onSolution}
          disabled={!problem}
          className="border-line bg-surface text-ink-soft hover:text-ink hover:border-brand inline-flex items-center justify-center gap-1.5 rounded-lg border px-3 py-2 text-[0.8125rem] font-semibold transition-colors disabled:opacity-40"
        >
          <Eye className="size-3.5" strokeWidth={2} aria-hidden />
          {showSolution ? "Hide" : "Solution"}
        </button>
      </div>

      {showHint && question.hint_md && (
        <p className="border-amber/30 bg-amber-wash text-ink-soft mt-3 rounded-lg border px-3 py-2.5 text-[0.8125rem] leading-relaxed">
          {question.hint_md}
        </p>
      )}
      {showSolution && problem && (
        <pre className="border-line bg-night mt-3 overflow-x-auto rounded-lg border p-3 font-mono text-[0.75rem] leading-[1.6] whitespace-pre-wrap text-white/90">
          {problem.solution_py}
        </pre>
      )}

      {problem && (
        <div className="mt-5">
          <p className="eyebrow mb-2">Sample cases</p>
          <ul className="space-y-2">
            {problem.tests.cases.slice(0, 3).map((testCase, i) => (
              <li
                key={i}
                className="border-line bg-surface rounded-lg border p-3 font-mono text-[0.75rem]"
              >
                <p className="text-ink-soft break-all">
                  <span className="text-ink-faint">in </span>
                  {displayArgs(testCase.args)}
                </p>
                <p className="text-leaf-deep mt-1 break-all">
                  <span className="text-ink-faint">out </span>
                  {display(testCase.expect)}
                </p>
              </li>
            ))}
          </ul>
          <p className="text-ink-faint mt-2 text-[0.75rem]">
            {problem.tests.cases.length} test cases in total.
          </p>
        </div>
      )}
    </div>
  );
}
