-- 0009 — projects: the graded, build-it half of the Agentic AI module.
--
-- A student submits a public repository rather than a zip. It is what they
-- would hand an employer, the reviewer can read the real folder structure and
-- real files, and there is nothing to unpack or scan.

create table if not exists public.projects (
  id         uuid primary key default gen_random_uuid(),
  module_id  uuid not null references public.modules (id) on delete cascade,
  position   integer not null,
  slug       text not null unique,
  title      text not null,
  summary    text not null,
  brief_md   text not null,
  rubric_md  text not null,
  is_published boolean not null default true
);

create table if not exists public.project_submissions (
  id           uuid primary key default gen_random_uuid(),
  project_id   uuid not null references public.projects (id) on delete cascade,
  user_id      uuid not null references auth.users (id) on delete cascade,
  repo_url     text not null,
  status       text not null default 'pending'
                 check (status in ('pending', 'passed', 'revise', 'error')),
  score        integer check (score between 0 and 10),
  feedback_md  text,
  model        text,
  files_seen   integer,
  created_at   timestamptz not null default now(),
  reviewed_at  timestamptz
);

create index if not exists project_submissions_user_idx
  on public.project_submissions (user_id, project_id, created_at desc);

alter table public.projects enable row level security;
alter table public.project_submissions enable row level security;

drop policy if exists projects_read on public.projects;
create policy projects_read on public.projects
  for select to authenticated
  using (is_published and (public.is_enrolled() or public.is_admin()));

drop policy if exists projects_admin_write on public.projects;
create policy projects_admin_write on public.projects
  for all using (public.is_admin()) with check (public.is_admin());

drop policy if exists project_submissions_select_own on public.project_submissions;
create policy project_submissions_select_own on public.project_submissions
  for select using (user_id = auth.uid() or public.is_admin());

-- Same rule as the Python attempts: a student may submit, never mark.
drop policy if exists project_submissions_insert_own on public.project_submissions;
create policy project_submissions_insert_own on public.project_submissions
  for insert to authenticated
  with check (
    user_id = auth.uid()
    and status = 'pending'
    and score is null
    and feedback_md is null
    and reviewed_at is null
  );

drop policy if exists project_submissions_admin_all on public.project_submissions;
create policy project_submissions_admin_all on public.project_submissions
  for all using (public.is_admin()) with check (public.is_admin());

-- The five briefs are seeded by 0009a, generated by scripts/build-projects.cjs
-- from content/projects/. Edit the markdown there and re-run the script.
