-- 0009a — the five project briefs.
--
-- Generated by scripts/build-projects.cjs from content/projects/.
-- Edit the markdown there and re-run the script; do not edit this file.


insert into public.projects
  (module_id, position, slug, title, summary, brief_md, rubric_md)
select m.id,
       1,
       $md$data-clean$md$,
       $md$A messy file, cleaned$md$,
       $md$Take a real, dirty dataset and produce a clean one — plus a defence of every decision you made.$md$,
       $md$Find a genuinely messy public dataset. Government open data portals, Kaggle and data.gov.in are full of them; pick something with at least a few thousand rows, mixed types and real missing values. Do not use a tutorial dataset that is already clean.

**Build**

- `notebooks/` or `src/` — the cleaning, as a script or notebook that runs top to bottom
- `data/` — the raw file (or a link to it if it is large) and the cleaned output
- `README.md` — what the data is, what was wrong with it, and what you did

**Answer at least five questions** of your own about the data using `groupby` and a join, and show the output.

**The marked part** is the README section headed "Decisions". For every missing-value choice, every de-duplication rule and every row you dropped, say what you did and why. "Filled with the median" is not enough; "filled with the median because it is 3% of rows, missing at random, and the column is skewed" is.

Include the assertions that check your work — row counts after merges, ranges, uniqueness.$md$,
       $md$Scored out of 10.

- **Runs (2)** — the code executes end to end on a fresh checkout
- **Cleaning is real (2)** — types fixed, dates parsed unambiguously, near-duplicate text normalised
- **Decisions defended (3)** — every choice named and justified, not just performed
- **Checks present (1)** — assertions on row counts, ranges, uniqueness
- **Questions answered (1)** — five real questions, with grouping and a join
- **Readable (1)** — a README someone else could follow$md$
from public.modules m
where m.slug = 'agentic-ai'
on conflict (slug) do update
  set title = excluded.title,
      summary = excluded.summary,
      brief_md = excluded.brief_md,
      rubric_md = excluded.rubric_md,
      position = excluded.position;


insert into public.projects
  (module_id, position, slug, title, summary, brief_md, rubric_md)
select m.id,
       2,
       $md$model-train$md$,
       $md$A model you can defend$md$,
       $md$Train a small model properly: an honest split, everything inside a pipeline, and a metric you chose before you saw the score.$md$,
       $md$Use your cleaned dataset from Project 1, or another one. Pick a real question — will a student pass, will an order be late, what will this cost.

**Build**

- A scikit-learn `Pipeline` containing every transformation. No scaling or imputing outside it.
- An honest split. Time-ordered data gets a time-ordered split, not a random one.
- A baseline to beat — predicting the majority class, or the mean.
- Cross-validation, reported as mean and spread.

**Write, in the README, before the results section**: which metric you are optimising and why that one matters for this problem. Then the confusion matrix and the classification report.

**Say what you would need to trust this in production.** More data, a different metric, a fairness check, a human in the loop — whatever is actually true.$md$,
       $md$Scored out of 10.

- **No leakage (3)** — every transformation inside the pipeline, split before anything is fitted
- **Honest evaluation (2)** — a real held-out set, cross-validation with spread reported
- **Metric justified (2)** — chosen and defended before the results, and appropriate to the class balance
- **Baseline (1)** — something to beat, and it is beaten
- **Limits stated (1)** — what would be needed to trust it
- **Runs (1)** — executes end to end$md$
from public.modules m
where m.slug = 'agentic-ai'
on conflict (slug) do update
  set title = excluded.title,
      summary = excluded.summary,
      brief_md = excluded.brief_md,
      rubric_md = excluded.rubric_md,
      position = excluded.position;


insert into public.projects
  (module_id, position, slug, title, summary, brief_md, rubric_md)
select m.id,
       3,
       $md$rag-pipeline$md$,
       $md$A RAG pipeline with a number$md$,
       $md$Retrieval over documents you choose, with a measured recall figure rather than a demo that looks convincing.$md$,
       $md$Pick a document set you actually care about — a textbook, your college regulations, a library's docs, a set of policies. Twenty or more documents.

**Build**

- Ingestion: load, chunk, embed, store. pgvector, Chroma or Qdrant — your choice, justified in the README.
- Retrieval: dense search at minimum. Hybrid and a reranker earn marks.
- Generation: an answer that cites its sources by number, and refuses when the sources do not contain the answer.

**The marked part is the evaluation.** Write 20 or more questions with the chunk that should answer each, and report `recall@5`. Then improve something — heading context in chunks, hybrid search, a reranker — and report the number again.

A README that says "it works well" scores nothing here. A README that says "recall@5 went from 0.55 to 0.80 after adding heading context to chunks" scores everything.$md$,
       $md$Scored out of 10.

- **Pipeline complete (2)** — ingest, chunk, embed, retrieve, generate
- **Chunking thought through (2)** — structure-aware, overlapping, context preserved in the chunk
- **Evaluation (3)** — 20+ questions, recall@k measured, before and after an improvement
- **Grounded answers (2)** — citations that resolve, and a refusal path when retrieval fails
- **Runs (1)** — a fresh checkout can reproduce the numbers$md$
from public.modules m
where m.slug = 'agentic-ai'
on conflict (slug) do update
  set title = excluded.title,
      summary = excluded.summary,
      brief_md = excluded.brief_md,
      rubric_md = excluded.rubric_md,
      position = excluded.position;


insert into public.projects
  (module_id, position, slug, title, summary, brief_md, rubric_md)
select m.id,
       4,
       $md$mcp-agent$md$,
       $md$An MCP server and an agent that uses it$md$,
       $md$Expose a real system as MCP tools, then drive it from an agent — including one tool that refuses.$md$,
       $md$Pick something with real state: a SQLite database, a task list, a filesystem folder, an API you have a key for.

**Build the server**

- Three or more tools, with descriptions written for the model — including at least one that says when *not* to use it
- One resource (a schema, a config, a reference document)
- One prompt template
- Runs over stdio, and works in the MCP Inspector

**Build the agent**

- Connects to your server, lists the tools, runs a real task end to end
- Caps its iterations
- Returns a useful message on a tool failure rather than raising

**One tool must refuse.** Something destructive or out of bounds — deleting, spending, sending. Show it declining, and say in the README what would have to be true for it to proceed.

Include a transcript of a working run.$md$,
       $md$Scored out of 10.

- **Server correct (3)** — tools, a resource and a prompt; works in the Inspector
- **Descriptions written for the model (2)** — specific, and at least one says when not to use the tool
- **Agent loop (2)** — connects, uses tools, capped iterations, recoverable tool errors
- **Refusal (2)** — a real guardrail, demonstrated, with the conditions stated
- **Transcript (1)** — evidence it ran$md$
from public.modules m
where m.slug = 'agentic-ai'
on conflict (slug) do update
  set title = excluded.title,
      summary = excluded.summary,
      brief_md = excluded.brief_md,
      rubric_md = excluded.rubric_md,
      position = excluded.position;


insert into public.projects
  (module_id, position, slug, title, summary, brief_md, rubric_md)
select m.id,
       5,
       $md$capstone$md$,
       $md$The whole thing$md$,
       $md$One system: retrieval, an MCP server, an agent, memory across sessions, and an evaluation set that proves it.$md$,
       $md$Everything from the four projects before this, in one place, solving one problem you choose. A study assistant over your own notes; a support agent over a product's documentation; a research assistant over a set of papers.

**It must have**

- **Retrieval** over a real corpus, with the evaluation from Project 3
- **An MCP server** exposing at least two tools the agent genuinely needs
- **An agent** that decides which to use, capped and guarded
- **Memory** — session history that survives a restart, and at least one fact carried between sessions
- **An evaluation set** of 15+ cases checking both the answer *and* which tools were called

**And a README that covers**

- Architecture, with a diagram of what calls what
- What it costs per conversation, measured, not estimated
- The failure modes you found and what you did about each
- What you would fix next, and why that first

This is the one to show people. Treat the README as the deliverable and the code as the evidence.$md$,
       $md$Scored out of 10.

- **All five pieces present (3)** — retrieval, MCP, agent, memory, evaluation
- **Evaluation checks tool calls (2)** — not just the text of the answer
- **Memory survives a restart (1)** — demonstrated, not asserted
- **Guardrails (1)** — iteration cap, timeouts, something irreversible gated
- **Cost measured (1)** — a real figure per conversation
- **README (2)** — architecture, failure modes found, what is next and why$md$
from public.modules m
where m.slug = 'agentic-ai'
on conflict (slug) do update
  set title = excluded.title,
      summary = excluded.summary,
      brief_md = excluded.brief_md,
      rubric_md = excluded.rubric_md,
      position = excluded.position;
